= Knowledge bases
A knowledge base is used mainly to define processors. A knowledge base may be written in one of the supported scripting languages. An alternative way of defining knowledge bases is to write them directly in Java. However, using a scripting knowledge base has advantages such as that a modified script knowledge base doesn't need recompilation.

There is a global namespace for all processors, regardless of the knowledge base they are defined in. When there is more than one processor of the same name in the engine, only the last enabled one will be registered. However, you can't enable a processor if an another one that has the same name and is of a different type has already been enabled.

Script knowledge base files are looked up: in the file system as a relative or absolute path, then in the classpath, then in the file system relative to the XML configuration file parent directory and then in the file system relative to the {sponge} home directory. This could be changed by providing a custom implementation of `KnowledgeBaseFileProvider` and passing it to the `setKnowledgeBaseFileProvider` method on the engine.

The order of loading knowledge bases preserves the order specified in the configuration. Likewise the order of loading files of the same knowledge base preserves the order specified in the configuration.

Scripting knowledge bases are read by interpreters. For every knowledge base there is one instance of an interpreter.

== Knowledge base file structure
Generally, script knowledge base files consist of a few parts:

. Import of modules and packages (from the scripting language or Java).
. Definitions of knowledge base processors (actions, filters, triggers, rules and correlators).
. Definitions of callback functions that will be invoked in particular situations:
+
.Callback functions
[cols="1,4"]
|===
|Function |Description

|`onInit()`
|Called once on the initialization of the knowledge base.

|`onLoad()`
|Called on the loading of the knowledge base and also every time the knowledge base is reloaded.

|`onStartup()`
|Called once after the startup of the engine (after `onInit()` and initial `onLoad()`).

|`onShutdown()`
|Called once before the shutdown of the engine.

|`onBeforeReload()`
|Called before every reloading of the knowledge base.

|`onAfterReload()`
|Called after every reloading of the knowledge base.
|===

{sponge} follows a convention that the names of all callback functions and methods start with `on`, e.g. `onStartup` for a knowledge base or `onConfigure` for a processor.

WARNING: You shouldn't place more than one callback function that has the same name in the same knowledge base (event in different files of that knowledge base). If there is more than one callback function that has the same name in the same knowledge base *only the last loaded function will be invoked*. Furthermore it could depend on the specific scripting language.

When {sponge} is starting, callback functions are invoked in the following order:

. executing all knowledge base files as scripts, i.e. executing the main body of the script files,
. `onInit()`,
. `onLoad()`,
. `onStartup()`.

Before `onStartup()` is invoked you will not be able to send events or access plugins. That is because the engine hasn't started fully yet.

When a knowledge base is reloaded, the callback functions are invoked in the following order:

. `onBeforeReload()` executed in the previous version of the reloaded knowledge base,
. executing all knowledge base files as scripts, i.e. executing the main body of the script files,
. `onLoad()` executed in the new version of the reloaded knowledge base,
. `onAfterReload()` executed in the new version of the reloaded knowledge base.

== Global variables
The following predefined global variables are available in all knowledge bases:

.Global variables
[cols="1,5"]
|===
|Global variable |Description

|`EPS`
|The facade to the {sponge} engine operations that provides methods to send events, manually enable or disable event processors etc. This variable represents an instance of a Java class implementing `org.openksavi.sponge.kb.KnowledgeBaseEngineOperations`. The name `EPS` stands for Event Processing System or Event Processing Sponge.
|===

For each plugin a global variable will be created. The name of this variable is the plugin name (i.e. the value configured as the plugin `name` attribute in the configuration).

=== Engine facade

.Important engine facade properties and methods
[cols="1,3"]
|===
|Property / Method |Description

|`kb`
|The knowledge base to which belongs the script using this variable. This value represents an object of a Java class implementing `org.openksavi.sponge.kb.KnowledgeBase` (for script knowledge base it is `org.openksavi.sponge.kb.ScriptKnowledgeBase`).

|`interpreter`
|The knowledge base interpreter that has read the script using this variable. Generally it is an implementation of `org.openksavi.sponge.kb.KnowledgeBaseInterpreter`. In the case of a scripting knowledge base it returns an implementation of `org.openksavi.sponge.kb.ScriptKnowledgeBaseInterpreter`.

|`engine`
|The engine. This is the reference to the actual implementation of the `Engine` interface.

|`logger`
|The logger instance associated with the knowledge base. The name of this logger has the following format: `sponge.kb.<language>.<knowledgeBaseName>.global`, e.g. `sponge.kb.python.kb1.global`. Please note, that event processors and plugins have their own loggers (they are referenced as `self.logger`).

|`enable()`
|Enables the processor.

|`enableAll()`
|Enables processors.

|`disable()`
|Disables the processor.

|`disableAll()`
|Disables processors.

|`enableJava()`
|Enables the Java-based processor.

|`enableJavaAll()`
|Enables Java-based processors.

|`disableJava()`
|Disables the Java-based processor.

|`disableJavaAll()`
|Disables Java-based processors.

|`Object call(String actionName, Object... args)`
|Calls registered action with arguments.

|`shutdown()`
|Shuts down the engine using the current thread.

|`requestShutdown()`
|Shuts down the engine using another thread.

|`reload()`
|Reloads script-based knowledge bases.

|`requestReload()`
|Reloads script-based knowledge bases using another thread.

|`boolean removeEvent(EventSchedulerEntry entry)`
|Removes the scheduled event.

|`getPlugin(String name)`
|Returns the plugin that has the specified name or `null` if there is no such plugin.

|`getPlugin(String name, Class<T> cls)`
|Returns the plugin that has the specified name and type or `null` if there is no such plugin.

|`getPlugin(Class<T> cls)`
|Returns the plugin that has the specified type or `null` if there is no such plugin.

|`EventDefinition event(String name)`
|Creates a new event definition.

|`EventDefinition event(String name, EventClonePolicy policy)`
|Creates a new event definition.

|`EventDefinition event(Event event)`
|Creates a new event definition.

|`boolean exists<Processor>(String name)`
|A set of methods returning `true` if a processor named `name` exists. The actual methods are: `existsFilter`, `existsTrigger`, `existsRule`, `existsCorrelator`, `existsAction`.

|`setVariable(String name, Object value)`
|Sets the engine scope variable.

|`Object getVariable(String name)`
|Returns the value of the engine scope variable. Throws exception if not found.

|`T getVariable(Class<T> cls, String name)`
|Returns the value of the engine scope variable. Throws exception if not found.

|`T getVariable(String name, T defaultValue)`
|Returns the value of the engine scope variable or `defaultValue` if not found.

|`T getVariable(Class<T> cls, String name, T defaultValue)`
|Returns the value of the engine scope variable or `defaultValue` if not found.

|`removeVariable(String name)`
|Removes the engine scope variable.

|`boolean existsVariable(String name)`
|Returns `true` if the engine scope variable named `name` exists.

|`setVariableIfNone(String name, Supplier<T> supplier)`
|Sets the engine scope variable if not set already.

|`version`
|The read-only property whose value is the engine version.

|`description`
|The read-only property whose value is the engine description.

|`statisticsSummary`
|The read-only property whose value is the engine statistics summary as a text.
|===

== User variables
A user variable could be defined in one of the two scopes:

* the engine scope,
* the knowledge base scope.

=== Engine scope
The engine scope variables could be accessed in any knowledge base.

.The engine scope variable examples
[source,python]
----
EPS.setVariable("soundTheAlarm", AtomicBoolean(False))
EPS.getVariable("soundTheAlarm").set(True)
----

TIP: The engine scope is the same as a {sponge} internal session scope. This is because currently there is only one session per a single {sponge} engine instance.

=== Knowledge base scope
The knowledge base scope variables may be accessed only in the knowledge base they are defined in.

.The knowledge base scope variable examples
[source,python]
----
hearbeatEventEntry = None

def onStartup():
    global hearbeatEventEntry
    hearbeatEventEntry = EPS.event("heartbeat").sendAfter(100, 1000)
----

== Loading knowledge base from an additional file
{sponge} gives the possibility to define a knowledge base in a few files. In order to do that, in the configuration file in the `<engine>` section you may define which files should be loaded by adding `<file>` tags to `<knowledgeBase>`. Additional files could also be loaded from a knowledge base level.

[source,python]
----
EPS.kb.load("triggers.py")
----

****
When the same name is used for a new processor, the previous definition will be replaced with the new one. However, this behavior could depend on the specific scripting language.
****

== Reloading
Sometimes a situation may happen that there will be a need for a dynamic modification of event processors, for example to add a new rule or remove an existing one. It is possible to do it without the need of shutting down and then starting the system again. However, depending on the specific interactions and taking into account differences in third-party implementations of scripting languages, it sometimes may lead to problems, so it should be used carefully.

When variables are used in a knowledge base and you don't want them to be changed after reloading of the knowledge base, you should place their definitions in `onInit()` callback functions rather than simply in the main script or in `onLoad()`. That is because the main script and `onLoad()` are always executed during reloading but `onInit()` function is not.

When reloading the system, the configuration file is not loaded again. If the changes in this file (e.g. registering a new plugin) are to be visible in the system, the only way is to restart.

When the {sponge} engine is being reloaded, the previously defined processors will not be removed from the registry. When a processor definition has changed in the file being reloaded, it will be auto-enabled (i.e. registered) once more with the new definition. If auto-enable is off, then `EPS.enable` method must be invoked. In that case `EPS.enable` should be placed in the `onLoad()` callback function.

IMPORTANT: If auto-enable is on (this is the default setting), then all processors will be enabled after reloading, even processors that have been manually disabled before.

WARNING: There is a limitation in reloading a knowledge base that defines event set processors (i.e. rules or correlators). When there are existing instances of event set processors, they will be dismissed.

== Use of many knowledge base files
As mentioned before, {sponge} provides the possibility to read a knowledge base from many files. Dividing a knowledge base into a few files allows in an easy way to separate some functionalities.

The order in which the files are loaded is important. The files will be loaded in such order in which they were placed in the configuration.

== Synchronization of processes in a knowledge base
{sponge} is a multi-threaded system. {sponge} engine operations are thread-safe. However, attention should be paid that processors defined in a knowledge base access any shared resources in a thread-safe way. This could be achieved in various ways using Java or scripting language mechanisms.


== Java knowledge base

.Example of sending events from within a Java knowledge base
[source,java]
----
public class TestKnowledgeBase extends JavaKnowledgeBase { // <1>

    @Override
    public void onStartup() {
        getEps().event("e1").set("mark", 1).sendAfter(1000); // <2>
    }
}
----
<1> The definition of the Java-based knowledge base class.
<2> Makes an event of type (name) `e1` with an attribute `mark` set to `1` and schedules it to be sent after `1` second.


== Scripting knowledge bases interoperability
There are some limitation in the interoperability between scripting knowledge bases:

* You shouldn't pass knowledge base interpreter scope variables from one knowledge base to an another. Even if they are written in the same scripting language. This is because each knowledge base has its own instance of an interpreter.
* Data structures used for communicating between different knowledge bases should by rather Java types or simple types that would be handled smoothly by Java implementations of scripting languages. For example you shouldn't use a script-based plugin in knowledge bases other than the one in which this plugin has been defined.
* Using more than one knowledge base written in the same scripting language may, in certain situations, also cause problems, due to the internal implementations of scripting language interpreters.

== Useful knowledge base commands

.Make and send a new event.
[source,python]
----
EPS.event("alarm").set("severity", 10).send()
----

.Print registered (i.e. enabled) triggers.
[source,python]
----
print EPS.engine.triggers
----

.Print registered rule groups.
[source,python]
----
print EPS.engine.ruleGroups
----

.Print instances of the first rule group.
[source,python]
----
print EPS.engine.ruleGroups[0].rules
----

.Print registered correlator groups.
[source,python]
----
print EPS.engine.correlatorGroups
----

.Shutdown using a new thread.
[source,python]
----
EPS.requestShutdown()
----

.Print the engine statistics summary.
[source,python]
----
print EPS.engine.statisticsManager.summary
----

For more information see {sponge} Javadoc.