= Actions
Actions provide functionality similar to synchronous functions. They may be used in many knowledge bases that are written in different languages.

The alias for the base class for script-based actions is `Action`. The base class for Java-based actions is `JAction`.

== Properties and methods
In addition to the inherited <<processor-methods,processor properties and methods>>, actions provide the following ones.

.Action properties and methods
[cols="1,5"]
|===
|Property / Method |Description

|`Object onCall (_dynamic arguments_)`
|The dynamic callback method that should be defined in an action. It will be invoked when an action is called, e.g.: `sponge.call()`. The behavior of this method is dynamic, i.e. custom actions define `onCall` methods with the arbitrary number of named arguments, for example `def onCall(self, value, text)`. This is the reason that the `Action` interface doesn't force any implementation of `onCall`. The result is an `Object`. The implementation of this method is mandatory.
|===

The `onConfigure` method in actions is not mandatory.

== Example in a script language
The code presented below defines the action named `EchoAction` that simply returns all arguments.

.Action example
[source,python]
----
class EchoAction(Action): # <1>
    def onCall(self, text): # <2>
        return text

def onStartup():
    result = sponge.call("EchoAction", "test") # <3>
    logger.debug("Action returned: {}", result)
----
<1> The definition of the action `EchoAction`. The action is represented by the class of the same name.
<2> The action `onCall` dynamic callback method that takes one argument `text` (in this case).
<3> Calls the action named `"EchoAction"` passing one argument.

.Console output
----
Action returned: test
----

== Example in Java
The code presented below defines the Java-based action named `JavaEchoAction`.

.Java action example
[source,java]
----
public class JavaEchoAction extends JAction { // <1>

    @Override
    public Object onCall(String text) { // <2>
        return text;
    }
}
----
<1> The definition of the action `JavaEchoAction`. The action is represented by the Java class of the same name.
<2> The action `onCall` callback method.

.Java action manual registration in the Python knowledge base
[source,python]
----
sponge.enableJava(JavaEchoAction)
----

== Arguments and result metadata
Actions may have metadata specified in the `onConfigure` method. Metadata may describe action arguments and a result. Metadata are not verified by the engine while performing an action call but could be interpreted by a client code or {sponge} plugins. For example they could be useful in a generic GUI that calls {sponge} actions. 

Metadata for arguments and a result support <<types, types>>.

.Argument metadata properties
[cols="1,3"]
|===
|Property |Description

|`name`
|A mandatory argument name.

|`type`
|A mandatory argument type.

|`displayName`
|An optional argument display name.

|`description`
|An optional argument description.

|`optional`
|A not mandatory flag specifying if this argument is optional (defaults to `false`). Optional arguments can be specified only as last in the argument list. Optional arguments are not required to be passed when calling an action.
|===

.Result metadata properties
[cols="1,3"]
|===
|Property |Description

|`type`
|A mandatory result type.

|`displayName`
|An optional result display name.

|`description`
|An optional result description.
|===

.Action metadata example
[source,python]
----
class UpperCase(Action):
    def onConfigure(self):
        self.displayName = "Convert to upper case"
        self.description = "Converts a string to upper case."
        self.features = {"visibility":True}
        self.argsMeta = [
            ArgMeta("text", StringType()).displayName("Text to upper case").description("The text that will be converted to upper case."),
            ArgMeta("optionalText", AnyType().nullable(True)).displayName("Text suffix").optional()
        ]
        self.resultMeta = ResultMeta(StringType()).displayName("Upper case text")
    def onCall(self, text, optionalText = None):
        return text.upper() + ( " " + optionalText.upper() if optionalText is not None else "")
----

.Action metadata example with multiple arguments
[source,python]
----
class MultipleArgumentsAction(Action):
    def onConfigure(self):
        self.displayName = "Multiple arguments action"
        self.argsMeta = [
            ArgMeta("stringArg", StringType().maxLength(10).format("ipAddress")),
            ArgMeta("integerArg", IntegerType().minValue(1).maxValue(100).defaultValue(50)),
            ArgMeta("anyArg", AnyType().nullable(True)),
            ArgMeta("stringListArg", ListType(StringType())),
            ArgMeta("decimalListArg", ListType(ObjectType("java.math.BigDecimal"))),
            ArgMeta("stringArrayArg", ObjectType("java.lang.String[]")),
            ArgMeta("javaClassArg", ObjectType("org.openksavi.sponge.examples.CustomObject")),
            ArgMeta("javaClassListArg", ListType(ObjectType("org.openksavi.sponge.examples.CustomObject"))),
            ArgMeta("binaryArg", BinaryType().mimeType("image/png").features({"width":28, "height":28, "color":"white"})),
        ]
        self.resultMeta = ResultMeta(BooleanType()).displayName("Boolean result")
    def onCall(self, stringArg, integerArg, anyArg, stringListArg, decimalListArg, stringArrayArg, javaClassArg, javaClassListArg, binaryArg):
        return True
----

For more information see `ArgMeta` and `ResultMeta`.

== Implementing interfaces
Actions may implement additional Java interfaces. It could be used to provide custom behavior of actions.

.Action implementing a Java interface
[source,python]
----
from org.openksavi.sponge.integration.tests.core import TestActionVisibiliy

class EdvancedAction(Action, TestActionVisibiliy): # <1>
    def onCall(self, text):
        return text.upper()
    def isVisible(self, context):
        return context == "day"
----
<1> The Java interface `TestActionVisibiliy` declares only one method `boolean isVisible(Object context)`.

