= {sponge} gRPC API server
The {sponge} gRPC API allows users to remotely subscribe to {sponge} events. The gRPC API server plugin (`GrpcApiServerPlugin`) starts the gRPC[https://grpc.io] server. The gRPC API server plugin requires the REST API plugin because it reuses some parts of the configuration.

The gRPC has been chosen to provide event subscriptions because the main remote {sponge} API, that is REST, has limited options for push notifications. The {sponge} gRPC API can be seen as an addition to the {sponge} REST API.

The default name of the gRPC API plugin (which can be used in knowledge bases) is `grpcApiServer`.

The plugin registeres the correlator (`GrpcApiSubscribeCorrelator`) in the {sponge} engine that listens to all {sponge} events and pushes them to subscribed clients. The client code can request that only events that have its data type registered will be pushed.

NOTE: Events are pushed online, i.e. if a client subscribes to an event type, only events that come after that time will be delivered.

.Key gRPC API plugin configuration parameters
[cols="1,1,4"]
|===
|Name |Type |Description

|`autoStart`
|`boolean`
|If `true` then the gRPC service will start when the plugin starts up. Defaults to `true`.

|`port`
|`Integer`
|The gRPC API port. Defaults to `null` i.e. the default port convention will be used.
|===

.The gRPC API server plugin XML configuration example
[source,xml,subs="verbatim,attributes"]
----
<sponge>
    <plugins>
        <plugin name="grpcApiServer" class="org.openksavi.sponge.grpcapi.server.GrpcApiServerPlugin">
            <configuration>
                <autoStart>false</autoStart>
            </configuration>
        </plugin>
    </plugins>
</sponge>
----

.The gRPC API server plugin Java configuration example
[source,java]
----
@Configuration
public static class Config extends SpongeCamelConfiguration {

    @Bean
    public SpongeEngine spongeEngine() {
        return SpringSpongeEngine.builder().plugins(camelPlugin(), restApiPlugin(), grpcApiPlugin())
                .config("sponge_config.xml").build();
    }

    @Bean
    public RestApiServerPlugin restApiPlugin() {
        return new RestApiServerPlugin();
    }

    @Bean
    public GrpcApiServerPlugin grpcApiPlugin() {
        return new GrpcApiServerPlugin();
    }
}
----

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/grpcapi/server/GrpcApiServerPlugin.html[`GrpcApiServerPlugin` Javadoc].

The gRPC API plugin provides support actions `GrpcApiManageSubscription` and `GrpcApiSendEvent` that can be called in the client code.

.Example use of the gRPC API support actions
[source,python]
----
def onStartup():
    # Enable support actions in this knowledge base.
    grpcApiServer.enableSupport(sponge)
----

[discrete]
== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-grpc-api-server</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

== Operations summary
The following table contains a summary of the gRPC API operations.

.The gRPC API operations summary
[cols="2,1,4"]
|===
|Name |URI |Description

|Get the Sponge version
|`GetVersion`
|Returns the Sponge version.

|Subscribe events
|`Subscribe`
|Subscribes to {sponge} events and returns a stream of events.
|===

== Interface specification

.The protobuf file for the gRPC API
[source]
----
include::{includesRootDir}/sponge-grpc-api-common/src/main/proto/sponge.proto[lines=17..-1]
----

== Configuration
The gRPC server port can be set by a Java system property `sponge.grpc.port` or by setting the `port` property of the plugin or by a convention. The convention is that the gRPC server port is the REST API port plus `1`, e.g. if the REST API port is `8080` then the gRPC API port will be `8081`.

== Error handling
An application error is returned to a client in a response message, just like in the REST API. An internal error is returned as a gRPC exception with a status.

== Security
If the REST API server is published as HTTPS, the gRPC server will be published as secure (TLS) using the same SSL/TLS configuration as the REST API.

.Example of generating a PEM file from the JKS keystore used by the REST API
[source,bash,subs="verbatim,attributes"]
----
keytool -exportcert -rfc -file remote_api_selfsigned.pem -keystore remote_api_selfsigned.jks -alias rest_api -keypass sponge -storepass sponge
----
