= Sponge REST API


[[_swagger_overview]]
== Overview

=== Version information
[%hardbreaks]
__Version__ : 1


=== URI scheme
[%hardbreaks]
__Host__ : localhost:1836
__BasePath__ : /
__Schemes__ : HTTP


=== Tags

* sponge.json/v1 : Sponge REST API




[[_swagger_paths]]
== Paths

[[_swagger_sponge-actionargs]]
=== Provide action arguments
....
POST sponge.json/v1/actionArgs
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**body** +
__required__|The provide action arguments request|<<_swagger_provideactionargsrequest,ProvideActionArgsRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|The provide action arguments response|<<_swagger_provideactionargsresponse,ProvideActionArgsResponse>>
|===


==== Tags

* sponge.json/v1


[[_swagger_sponge-actions]]
=== Get actions
....
POST sponge.json/v1/actions
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**body** +
__required__|Get actions request|<<_swagger_getactionsrequest,GetActionsRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|The get actions response|<<_swagger_getactionsresponse,GetActionsResponse>>
|===


==== Tags

* sponge.json/v1


[[_swagger_sponge-call]]
=== Call an action
....
POST sponge.json/v1/call
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**body** +
__required__|Call action request|<<_swagger_actioncallrequest,ActionCallRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|The action call response|<<_swagger_actioncallresponse,ActionCallResponse>>
|===


==== Tags

* sponge.json/v1


[[_swagger_sponge-knowledgebases]]
=== Get knowledge bases
....
POST sponge.json/v1/knowledgeBases
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**body** +
__required__|Get knowledge bases request|<<_swagger_getknowledgebasesrequest,GetKnowledgeBasesRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|The get knowledge bases response|<<_swagger_getknowledgebasesresponse,GetKnowledgeBasesResponse>>
|===


==== Tags

* sponge.json/v1


[[_swagger_sponge-login]]
=== Login
....
POST sponge.json/v1/login
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**body** +
__required__|Login request|<<_swagger_loginrequest,LoginRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|The login response|<<_swagger_loginresponse,LoginResponse>>
|===


==== Tags

* sponge.json/v1


[[_swagger_sponge-logout]]
=== Logout
....
POST sponge.json/v1/logout
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**body** +
__required__|Logout request|<<_swagger_logoutrequest,LogoutRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|The logout response|<<_swagger_logoutresponse,LogoutResponse>>
|===


==== Tags

* sponge.json/v1


[[_swagger_sponge-reload]]
=== Reload knowledge bases
....
POST sponge.json/v1/reload
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**body** +
__required__|Reload knowledge bases request|<<_swagger_reloadrequest,ReloadRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|The reload response|<<_swagger_reloadresponse,ReloadResponse>>
|===


==== Tags

* sponge.json/v1


[[_swagger_sponge-send]]
=== Send a new event
....
POST sponge.json/v1/send
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**body** +
__required__|Send event request|<<_swagger_sendeventrequest,SendEventRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|The send event response|<<_swagger_sendeventresponse,SendEventResponse>>
|===


==== Tags

* sponge.json/v1


[[_swagger_sponge-version]]
=== Get the Sponge version
....
POST sponge.json/v1/version
....


==== Parameters

[options="header", cols=".^2a,.^3a,.^9a,.^4a"]
|===
|Type|Name|Description|Schema
|**Body**|**body** +
__required__|Get Sponge version request|<<_swagger_getversionrequest,GetVersionRequest>>
|===


==== Responses

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP Code|Description|Schema
|**200**|The Sponge version response|<<_swagger_getversionresponse,GetVersionResponse>>
|===


==== Tags

* sponge.json/v1




[[_swagger_definitions]]
== Definitions

[[_swagger_processorqualifiedversion]]
=== ProcessorQualifiedVersion

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**knowledgeBaseVersion** +
__optional__|integer (int32)
|**processorVersion** +
__optional__|integer (int32)
|===


[[_swagger_provideactionargsrequest]]
=== ProvideActionArgsRequest
A provide action arguments request


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The request id|string
|**username** +
__optional__|The user name|string
|**password** +
__optional__|The user password|string
|**authToken** +
__optional__|The authentication token|string
|**name** +
__required__|The action name|string
|**argNames** +
__optional__|The names of action arguments to provide|< string > array
|**current** +
__optional__|The current values of action arguments in a client code|< string, object > map
|**qualifiedVersion** +
__optional__|The action expected qualified version|<<_swagger_processorqualifiedversion,ProcessorQualifiedVersion>>
|===


[[_swagger_provideactionargsresponse]]
=== ProvideActionArgsResponse
A provide action arguments response


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The corresponding request id|string
|**errorCode** +
__optional__|The error code|string
|**errorMessage** +
__optional__|The error message|string
|**detailedErrorMessage** +
__optional__|The detailed error message|string
|**provided** +
__required__|The provided action arguments|< string, <<_swagger_argvalueobject,ArgValueObject>> > map
|===


[[_swagger_argvalue]]
=== ArgValue

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**value** +
__optional__|object
|**valuePresent** +
__optional__|boolean
|**annotatedValueSet** +
__optional__|< <<_swagger_annotatedvalueobject,AnnotatedValueObject>> > array
|**valueSet** +
__optional__|< object > array
|===


[[_swagger_annotatedvalue]]
=== AnnotatedValue

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**value** +
__optional__|object
|**label** +
__optional__|string
|**description** +
__optional__|string
|**features** +
__optional__|< string, object > map
|===


[[_swagger_argvalueobject]]
=== ArgValueObject

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**value** +
__optional__|object
|**valuePresent** +
__optional__|boolean
|**annotatedValueSet** +
__optional__|< <<_swagger_annotatedvalueobject,AnnotatedValueObject>> > array
|**valueSet** +
__optional__|< object > array
|===


[[_swagger_annotatedvalueobject]]
=== AnnotatedValueObject

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**value** +
__optional__|object
|**label** +
__optional__|string
|**description** +
__optional__|string
|**features** +
__optional__|< string, object > map
|===


[[_swagger_getactionsrequest]]
=== GetActionsRequest
A get actions request


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The request id|string
|**username** +
__optional__|The user name|string
|**password** +
__optional__|The user password|string
|**authToken** +
__optional__|The authentication token|string
|**name** +
__optional__|The action name or the regular expression (compatible with https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html)|string
|**metadataRequired** +
__optional__|The metadata required flag|boolean
|===


[[_swagger_knowledgebasemeta]]
=== KnowledgeBaseMeta
A knowledge base metadata


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**name** +
__required__|The knowledge base name|string
|**label** +
__optional__|The knowledge base label|string
|**description** +
__optional__|The knowledge base description|string
|**version** +
__optional__|The knowledge base version|integer (int32)
|===


[[_swagger_actionmeta]]
=== ActionMeta
An action metadata


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**name** +
__required__|The action name|string
|**label** +
__optional__|The action label|string
|**description** +
__optional__|The action description|string
|**knowledgeBase** +
__required__|The action knowledge base metadata|<<_swagger_knowledgebasemeta,KnowledgeBaseMeta>>
|**features** +
__required__|The action features|< string, object > map
|**argsMeta** +
__optional__|The action arguments metadata|< <<_swagger_actionargmeta,ActionArgMeta>> > array
|**resultMeta** +
__optional__|The action result metadata|<<_swagger_actionresultmeta,ActionResultMeta>>
|**qualifiedVersion** +
__optional__|The action qualified version|<<_swagger_processorqualifiedversion,ProcessorQualifiedVersion>>
|===


[[_swagger_argprovided]]
=== ArgProvided

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**value** +
__optional__|boolean
|**valueSet** +
__optional__|boolean
|**depends** +
__optional__|< string > array
|**readOnly** +
__optional__|boolean
|**overwrite** +
__optional__|boolean
|===


[[_swagger_actionargmeta]]
=== ActionArgMeta
An action argument metadata


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**name** +
__required__|The action argument name|string
|**type** +
__required__|The action argument type|<<_swagger_datatype,DataType>>
|**label** +
__optional__|The action argument label|string
|**description** +
__optional__|The action argument description|string
|**optional** +
__optional__|Optional argument|boolean
|**provided** +
__optional__|The provided argument specification|<<_swagger_argprovided,ArgProvided>>
|===


[[_swagger_getactionsresponse]]
=== GetActionsResponse
A get actions response


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The corresponding request id|string
|**errorCode** +
__optional__|The error code|string
|**errorMessage** +
__optional__|The error message|string
|**detailedErrorMessage** +
__optional__|The detailed error message|string
|**actions** +
__required__|The available actions|< <<_swagger_actionmeta,ActionMeta>> > array
|===


[[_swagger_datatype]]
=== DataType

[options="header", cols=".^3a,.^4a"]
|===
|Name|Schema
|**kind** +
__optional__|enum (STRING, NUMBER, INTEGER, BOOLEAN, BINARY, ANY, VOID, OBJECT, LIST, MAP, ANNOTATED)
|**format** +
__optional__|string
|**defaultValue** +
__optional__|object
|**nullable** +
__optional__|boolean
|**features** +
__optional__|< string, object > map
|===


[[_swagger_actionresultmeta]]
=== ActionResultMeta
An action result metadata


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**type** +
__required__|The action result type|<<_swagger_datatype,DataType>>
|**label** +
__optional__|The action result label|string
|**description** +
__optional__|The action result description|string
|===


[[_swagger_actioncallrequest]]
=== ActionCallRequest
An action call request


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The request id|string
|**username** +
__optional__|The user name|string
|**password** +
__optional__|The user password|string
|**authToken** +
__optional__|The authentication token|string
|**name** +
__required__|The action name|string
|**args** +
__optional__|The action arguments|< object > array
|**qualifiedVersion** +
__optional__|The action expected qualified version|<<_swagger_processorqualifiedversion,ProcessorQualifiedVersion>>
|===


[[_swagger_actioncallresponse]]
=== ActionCallResponse
An action call response


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The corresponding request id|string
|**errorCode** +
__optional__|The error code|string
|**errorMessage** +
__optional__|The error message|string
|**detailedErrorMessage** +
__optional__|The detailed error message|string
|**result** +
__required__|The action result|object
|===


[[_swagger_getknowledgebasesrequest]]
=== GetKnowledgeBasesRequest
A get knowledge bases request


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The request id|string
|**username** +
__optional__|The user name|string
|**password** +
__optional__|The user password|string
|**authToken** +
__optional__|The authentication token|string
|===


[[_swagger_getknowledgebasesresponse]]
=== GetKnowledgeBasesResponse
A get knowledge bases response


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The corresponding request id|string
|**errorCode** +
__optional__|The error code|string
|**errorMessage** +
__optional__|The error message|string
|**detailedErrorMessage** +
__optional__|The detailed error message|string
|**knowledgeBases** +
__required__|The available knowledge bases|< <<_swagger_knowledgebasemeta,KnowledgeBaseMeta>> > array
|===


[[_swagger_loginrequest]]
=== LoginRequest
A login request


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The request id|string
|**username** +
__optional__|The user name|string
|**password** +
__optional__|The user password|string
|**authToken** +
__optional__|The authentication token|string
|===


[[_swagger_loginresponse]]
=== LoginResponse
A login response


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The corresponding request id|string
|**errorCode** +
__optional__|The error code|string
|**errorMessage** +
__optional__|The error message|string
|**detailedErrorMessage** +
__optional__|The detailed error message|string
|**authToken** +
__required__|The authentication token|string
|===


[[_swagger_logoutrequest]]
=== LogoutRequest
A logout request


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The request id|string
|**username** +
__optional__|The user name|string
|**password** +
__optional__|The user password|string
|**authToken** +
__optional__|The authentication token|string
|===


[[_swagger_logoutresponse]]
=== LogoutResponse
A logout response


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The corresponding request id|string
|**errorCode** +
__optional__|The error code|string
|**errorMessage** +
__optional__|The error message|string
|**detailedErrorMessage** +
__optional__|The detailed error message|string
|===


[[_swagger_reloadrequest]]
=== ReloadRequest
A reload request


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The request id|string
|**username** +
__optional__|The user name|string
|**password** +
__optional__|The user password|string
|**authToken** +
__optional__|The authentication token|string
|===


[[_swagger_reloadresponse]]
=== ReloadResponse
A reload response


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The corresponding request id|string
|**errorCode** +
__optional__|The error code|string
|**errorMessage** +
__optional__|The error message|string
|**detailedErrorMessage** +
__optional__|The detailed error message|string
|===


[[_swagger_sendeventrequest]]
=== SendEventRequest
A send event request


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The request id|string
|**username** +
__optional__|The user name|string
|**password** +
__optional__|The user password|string
|**authToken** +
__optional__|The authentication token|string
|**name** +
__required__|The event name|string
|**attributes** +
__optional__|The event attributes|< string, object > map
|===


[[_swagger_sendeventresponse]]
=== SendEventResponse
A send event response


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The corresponding request id|string
|**errorCode** +
__optional__|The error code|string
|**errorMessage** +
__optional__|The error message|string
|**detailedErrorMessage** +
__optional__|The detailed error message|string
|**eventId** +
__required__|The event id|string
|===


[[_swagger_getversionrequest]]
=== GetVersionRequest
A get version request


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The request id|string
|**username** +
__optional__|The user name|string
|**password** +
__optional__|The user password|string
|**authToken** +
__optional__|The authentication token|string
|===


[[_swagger_getversionresponse]]
=== GetVersionResponse
A get version response


[options="header", cols=".^3a,.^11a,.^4a"]
|===
|Name|Description|Schema
|**id** +
__optional__|The corresponding request id|string
|**errorCode** +
__optional__|The error code|string
|**errorMessage** +
__optional__|The error message|string
|**detailedErrorMessage** +
__optional__|The detailed error message|string
|**version** +
__required__|The Sponge version|string
|===





