= {sponge} REST API server
The REST API server provides a {sponge} REST API service. The server plugin (`RestApiServerPlugin`) uses Apache Camel REST DSL in order to configure the JSON/REST service.

The default name of the REST API plugin (which can be used in knowledge bases) is `restApiServer`.

.Key REST API plugin configuration parameters
[cols="1,1,4"]
|===
|Name |Type |Description

|`autoStart`
|`boolean`
|If `true` then the REST service will start when the plugin starts up. Defaults to `true`.

|`restComponentId`
|`String`
|The Camel REST component id. Defaults to `"jetty"`.

|`host`
|`String`
|The REST API host. It can be overwritten by a Java system property `sponge.restApiServer.host`.

|`port`
|`int`
|The REST API port. Defaults to `1836`. It can be overwritten by a Java system property `sponge.restApiServer.port`.

|`path`
|`String`
|The REST API path. Defaults to `null`. It can be overwritten by a Java system property `sponge.restApiServer.path`.

|`name`
|`String`
|The REST API name. It can be overwritten by a Java system property `sponge.restApiServer.name`.

|`description`
|`String`
|The REST API description.

|`license`
|`String`
|The license text of a particular REST API service.

|`prettyPrint`
|`boolean`
|The pretty print option. Defaults to `false`.

|`publicActions`
|`List<ProcessorQualifiedName>`
|Public actions.

|`publicEvents`
|`List<String>`
|Public event names.

|`sslConfiguration`
|`SslConfiguration`
|The SSL configuration.

|`publishReload`
|`boolean`
|If `true` then the reload operation will be published. Defaults to `false`.

|`routeBuilderClass`
|`String`
|The name of the class extending `RestApiRouteBuilder` (which is the default route builder).

|`apiServiceClass`
|`String`
|The `RestApiService` implementation class name. Defaults to `DefaultRestApiService`.

|`securityServiceClass`
|`String`
|The `RestApiSecurityService` implementation class name. Defaults to `NoSecuritySecurityService`.

|`authTokenServiceClass`
|`String`
|The `RestApiAuthTokenService` implementation class name. The default implementation is `JwtRestApiAuthTokenService` that uses JSON Web Token (JWT) for Java https://github.com/jwtk/jjwt[JJWT] library. Note that tokens used by the default implementation are signed but not encrypted.

|`authTokenExpirationDurationSeconds`
|`Long`
|The duration (in seconds) after which an authentication token will expire. The value `null` or less than or equal to 0 means infinity. Defaults to 30 minutes.

|`includeResponseTimes`
|`boolean`
|The flag specifying if a response header should have request and response time set. Defaults to `true`.

|`registerServiceDiscovery`
|`boolean`
|The flag specifying if the service should be registered in a service discovery. It allows client applications to automatically find nearby (i.e. on the local network) {sponge} services. Defaults to `true`.

|`registerServiceDiscovery`
|`boolean`
|The flag specifying if the service should be registered in a service discovery. Defaults to `false`. It can be overwritten by a Java system property `sponge.restApiServer.registerServiceDiscovery`.

|`serviceDiscoveryUrl`
|`String`
|The service URL used in a service discovery. It can be overwritten by a Java system property `sponge.restApiServer.serviceDiscoveryUrl`. This property automatically sets the `registerServiceDiscovery` flag to `true` as well.
|===

.The REST API server plugin XML configuration example
[source,xml,subs="verbatim,attributes"]
----
<sponge>
    <plugins>
        <plugin name="restApiServer" class="org.openksavi.sponge.restapi.server.RestApiServerPlugin">
            <configuration>
                <port>1836</port>
                <autoStart>false</autoStart>
            </configuration>
        </plugin>
    </plugins>
</sponge>
----

.The REST API server plugin Java configuration example
[source,java]
----
@Configuration
public static class Config extends SpongeCamelConfiguration {

    @Bean
    public SpongeEngine spongeEngine() {
        return SpringSpongeEngine.builder().plugins(camelPlugin(), restApiPlugin())
                .config("sponge_config.xml").build();
    }

    @Bean
    public RestApiServerPlugin restApiPlugin() {
        RestApiServerPlugin plugin = new RestApiServerPlugin();
        plugin.setSecurityService(restApiSecurityService());

        return plugin;
    }

    @Bean
    public RestApiSecurityService restApiSecurityService() {
        return new SimpleInMemorySecurityService();
    }
}
----

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/restapi/server/RestApiServerPlugin.html[`RestApiServerPlugin` Javadoc].

[discrete]
== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-rest-api-server</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

Depending on the REST Camel component, you should add a corresponding dependency, e.g. `camel-jetty` for Jetty, `camel-servlet` for a generic servlet. For more information see the Camel documentation.

== Custom operations
You can define a custom REST API operation (using the `ActionDelegateRestApiOperation` class in the route builder) that delegates a REST API request to an action call (e.g. to allow implementing an operation body in a scripting language but keeping a static REST interface).

== OpenAPI specification
After starting the plugin, the online API specification in the https://swagger.io[OpenAPI 2.0 (Swagger)] JSON format will be accesible.

== JSON/Java mapping
The REST API uses the https://github.com/FasterXML/jackson[Jackson] library to process JSON. A transformation of action arguments and result values is determined by types specified in the corresponding action arguments and result metadata.

The default Jackson configuration for the REST API sets the ISO8601 format for dates.

NOTE: A `BinaryType` value is marshalled to a base64 encoded string. This encoding adds significant overhead and should be used only for relatively small binary data.

== Session
For each request the REST API service creates a thread local session. The session provides access to a logged user and a Camel exchange for a thread handling the request. The session can be accessed in an action via the REST API server plugin.

.Accessing the REST API session
[source,python]
----
class LowerCaseHello(Action):
    def onConfigure(self):
        self.withLabel("Hello with lower case")
        self.withArg(StringType("text").withLabel("Text to lower case")).withResult(StringType().withLabel("Lower case text"))
    def onCall(self, text):
        return "Hello " + restApiServer.session.user.name + ": " + text.lower()
----

In order to handle a session lifecycle you can implement and set the on session open and the on session close listeners in the `RestApiService`.

== Security
The REST API provides only simple security out of the box and only if turned on. All requests allow passing a user name and a password. If the user name is not set, the _anonymous_ user is assumed.

A user may have roles.

You may set a security strategy by providing an implementation of the `RestApiSecurityService` interface. You may find a few examples of such implementations in the source code. In production mode we suggest using https://spring.io/projects/spring-security[Spring Security] and configure Camel security. An advanced security configuration has to be set up in Java rather than in a {sponge} XML configuration file. You may implement various authorization scenarios, for example using HTTP headers that are available in a Camel exchange.

[[rest-api-server-simple-security-strategy]]
=== Simple security strategy
The simple security strategy uses in-memory user data or user data stored in a password file. User privileges and access to knowledge bases, actions and events are verified by calling {sponge} actions (`RemoteApiIsActionPublic`, `RemoteApiIsEventPublic`, `RemoteApiCanUseKnowledgeBase`, `RemoteApiCanSendEvent`, `RemoteApiCanSubscribeEvent`). Passwords are stored as SHA-512 hashes.

.Example of the Remote API simple security
[source,python]
----
# Simple access configuration: role -> knowledge base names regexps.
ROLES_TO_KB = { "admin":[".*"], "anonymous":["demo", "digits", "demoForms.*"]}
# Simple access configuration: role -> event names regexps.
ROLES_TO_SEND_EVENT = { "admin":[".*"], "anonymous":[]}
ROLES_TO_SUBSCRIBE_EVENT = { "admin":[".*"], "anonymous":["notification.*"]}

class RemoteApiCanUseKnowledgeBase(Action):
    def onCall(self, userContext, kbName):
        return restApiServer.canAccessResource(ROLES_TO_KB, userContext, kbName)

class RemoteApiCanSendEvent(Action):
    def onCall(self, userContext, eventName):
        return restApiServer.canAccessResource(ROLES_TO_SEND_EVENT, userContext, eventName)

class RemoteApiCanSubscribeEvent(Action):
    def onCall(self, userContext, eventName):
        return restApiServer.canAccessResource(ROLES_TO_SUBSCRIBE_EVENT, userContext, eventName)

def onStartup():
    # Load users from a password file.
    restApiServer.service.securityService.loadUsers()
----

A password file is specified by a `password.file` configuration property.

For more information see examples in the source code.

=== Adding a REST API user to a password file
A REST API user password file is a way to configure users for a {sponge} REST API simple security strategy. Each user has its entry in a separate line. The entry contains colon-separated: a username, a comma-separated list of groups and a hashed password.

.Example of a password file
[source,bash,subs="verbatim,attributes"]
----
admin:admin:86975030682e27eca6fa4fb90e9d4b4aa3b3efc381149385347c7573b0b7002d48b1462c7f2e20db7a48cffdcc329bb1b6868551b7372d19a2781571919cc831
----

The best way of adding a REST API user to a password file is to use a predefined knowledge base `kb_add_remote_api_user.py` in a Docker container. The knowledge base requires an argument specifying a password file.

.Adding a REST API user
[source,bash,subs="verbatim,attributes"]
----
docker run -it --rm -v `pwd`:/opt/tmp openksavi/sponge -k "classpath*:/org/openksavi/sponge/restapi/server/kb_add_remote_api_user.py" -q /opt/tmp/password.txt
----

A password can be generated manually and added to a password file as well.

.Generating a password hash manually
[source,bash,subs="verbatim,attributes"]
----
# Note that the user name must be lower case.
echo -n username-password | shasum -a 512 | awk '{ print $1 }'
----

== HTTPS
In production mode you should configure HTTPS. Otherwise your passwords could be sent in plain text over the network as a part of the REST API JSON requests.

== Service discovery
The {sponge} REST API can be registered using the the mDNS/DNS-SD service discovery to provide a zero-configuration connection setup for {sponge} REST API clients in a local network.

== Environment

=== Standalone
This is the default configuration that uses the embedded Jetty server.

=== Servlet container
The {sponge} REST API service may also be deployed into a servlet container (e.g. https://tomcat.apache.org[Tomcat]) as a web application. See the <<rest-api-demo-service,REST API Demo Service>> example.
