= Examples

== News project
This project shows how to process news as events. It is placed in `sponge-examples-project-news` (see {sourcesUrl}/sponge-examples-projects/sponge-examples-project-news[sources]).

Event flow:

* News are manually generated and sent as {sponge} events named `news` in `onStartup` function of the knowledge base named `newsGenerator`. Each event has custom attributes: `source` and `title`.
* Every event named `news` is filtered to discard news that have empty or short (according to `newsFilterWordThreshold` configuration property) titles. This is done by `NewsFilter` filter.
* Events named `news` are logged by `LogNewsTrigger` trigger.
* When there are no new `news` events (that passed filters) for a specified time, then `alarm` event is sent. This is done by `NoNewNewsAlarmRule` rule.
* `LatestNewsCorrelator` correlator listens to `news` events and stores the latest news in `storagePlugin` plugin in a Python `deque`. The number of latest news is configured as `latestNewsMaxSize` property.
* When `alarm` event happens, this fact is logged by `AlarmTrigger` trigger using `echoPlugin` plugin and `EmphasizeAction` action.


.Main class - NewsExampleMain
[source,java]
----
include::{completeExamplesProject}/sponge-examples-project-news/src/main/java/org/openksavi/sponge/examples/project/news/NewsExampleMain.java[lines=17..-1]
----

.{sponge} XML configuration file - config.xml
[source,xml]
----
include::{completeExamplesProject}/sponge-examples-project-news/config/config.xml[]
----

.Python-based knowledge base 'main' file - main_event_processors.py
[source,python]
----
include::{completeExamplesProject}/sponge-examples-project-news/kb/main_event_processors.py[lines=5..-1]
----

.Python-based knowledge base 'main' file - main_functions.py
[source,python]
----
include::{completeExamplesProject}/sponge-examples-project-news/kb/main_functions.py[lines=5..-1]
----

.Python-based knowledge base 'main' file - main_plugins.py
[source,python]
----
include::{completeExamplesProject}/sponge-examples-project-news/kb/main_plugins.py[lines=5..-1]
----

.JavaScript-based knowledge base 'actions' file - actions.js
[source,python]
----
include::{completeExamplesProject}/sponge-examples-project-news/kb/actions.js[actions.js]
----

.Python-based knowledge base that generates sample news - news_generator.py
[source,python]
----
include::{completeExamplesProject}/sponge-examples-project-news/kb/news_generator.py[lines=5..-1]
----

.Java-based plugin class - MultiEchoPlugin
[source,java]
----
include::{completeExamplesProject}/sponge-examples-project-news/src/main/java/org/openksavi/sponge/examples/project/news/MultiEchoPlugin.java[lines=17..-1]
----

== Camel RSS News project
This example is an enhancement over the News project example. It is placed in `sponge-examples-project-camel-rss-news` (see {sourcesUrl}/sponge-examples-projects/sponge-examples-project-camel-rss-news[sources]).

The main change here is that news are acquired as RSS feeds from news services: BBC and CNN. Reading RSS feeds and transformation to {sponge} events is performed in a Camel route. {sponge} acts as a producer in this Camel route. This example shows {sponge} as a consumer in other Camel routes as well.

This example also presents integration with Spring framework. A service provided as a Spring bean is accessed from the script knowledge base.

Knowledge bases `main` and `actions` that existed in the News project example are not changed. This is because the main processing is independent of the input and output interfaces, protocols or data structures. Internal events (in this case `news` events) are normalized.

Event flow:

* RSS feeds are read from external sources, transformed to {sponge} events and sent to the {sponge} engine. This is done in Camel routes.
* The `main` knowledge base related event flow is the same as in the previous example.
* After the time configured as a property `durationOfReadingRss` Camel routes that read RSS feeds from external sources are stopped. It simulates lack of new news. This is done in the `simulator` knowledge base.
* When `alarm` event happens, not only `AlarmTrigger` (as described in the previous example) handles that event, but here also `ForwardAlarmTrigger` trigger, defined in the `consumer` knowledge base. It sends an alarm message to:
** all Camel endpoints that use the Sponge engine as a consumer in their routes,
** to a specific endpoint given as URI.

.Main class - CamelRssNewsExampleMain
[source,java]
----
include::{completeExamplesProject}/sponge-examples-project-camel-rss-news/src/main/java/org/openksavi/sponge/examples/project/camelrssnews/CamelRssNewsExampleMain.java[lines=17..-1]
----

.Spring Java configuration - SpringConfiguration
[source,java]
----
include::{completeExamplesProject}/sponge-examples-project-camel-rss-news/src/main/java/org/openksavi/sponge/examples/project/camelrssnews/SpringConfiguration.java[lines=17..-1]
----

.{sponge} XML configuration file - config.xml
[source,xml]
----
include::{completeExamplesProject}/sponge-examples-project-camel-rss-news/config/config.xml[]
----

.Python-based extended configuration - config.py
[source,python]
----
include::{completeExamplesProject}/sponge-examples-project-camel-rss-news/kb/config.py[lines=5..-1]
----

.Python-based knowledge base that sends messages to Camel as a consumer - consumer.py
[source,python]
----
include::{completeExamplesProject}/sponge-examples-project-camel-rss-news/kb/consumer.py[lines=5..-1]
----

[[rest-api-demo-service]]
== REST API Demo Service project
The {sourcesUrl}/sponge-examples-projects/sponge-examples-project-demo-service[Demo Service] use case shows how to deploy the REST API as a servlet. It uses <<rest-api-server-simple-security-strategy,the simple security strategy>>. There are a few options to run the demo.

[discrete]
=== Using the hosted Demo Service
The Demo Service hosted at `https://spongedemoapi.openksavi.org` provides an anonymous access to the {sponge} demo. It is used by the {sponge} mobile client application as a predefined connection. You can also connect to the service using command line tools.

[source,bash,subs="verbatim,attributes"]
----
curl -H "Content-type:application/json" https://spongedemoapi.openksavi.org/version
----

[discrete]
=== Running in Docker
The Docker image `openksavi/sponge-demo` contains a predefined REST API Demo Service running in Tomcat. It can be used as a {sponge} mobile client application playground in your local environment.

NOTE: This image doesn't work on Raspberry Pi. To run the Demo Service on Raspberry Pi see the next chapter.

NOTE: The predefined file `password.txt` contains the hashed, insecure password `password` for the user `admin`. You should change it or use this demo only for tests in a secure network.

.Initialization and configuration
[source,bash,subs="verbatim,attributes"]
----
# Run the demo in Docker using the predefined {sponge} configuration.
docker run --name sponge-demo -it --rm -p 8080:8080 -p 8081:8081 openksavi/sponge-demo

# Copy the predefined {sponge} configuration to the host in order to modify knowledge base files.
docker cp sponge-demo:/opt/sponge/ .

# Stop the running container.
docker stop sponge-demo

# Start a new container using a new {sponge} configuration located in the host filesystem.
# The configurtion directory is expected to have the sponge.xml file.
docker run --name sponge-demo -it --rm -p 8080:8080 -p 8081:8081 --mount type=bind,source="$(pwd)/sponge",target=/opt/sponge openksavi/sponge-demo
----

The port `8080` is used by the REST API and the port `8081` is used by the gRPC API.

.Verification
[source,bash,subs="verbatim,attributes"]
----
# Test the service.
curl http://localhost:8080/version

# Invoke shell in the container.
docker exec -it sponge-demo /bin/bash
----

.Development process
[source,bash,subs="verbatim,attributes"]
----
# Modify the {sponge} configuration in the host.
vi sponge_demo.py
# For example add a new action.
class HelloWorld(Action):
    def onConfigure(self):
        self.withLabel("Hello World").withDescription("The action created in a running Docker container.")
        self.withNoArgs().withResult(StringType().withLabel("Greeting"))
        self.withFeature("icon", "human-greeting")
    def onCall(self):
        return "Hello World!"

# Reload the knowledge bases as admin via a commandline tool or the {sponge} mobile client application.
curl -X POST -H "Content-type:application/json" http://localhost:8080/reload -d '{"header":{"username":"admin","password":"password"}}'

# Refresh actions in the {sponge} mobile client application.
# The new action will be visible in the action list.
----

[discrete]
=== Running in Docker on Raspberry Pi
The Docker image `openksavi/sponge-demo-lite` contains the REST API Demo Service Light that can be run on Raspberry Pi. It can be used as a {sponge} mobile client application playground in your Raspberry Pi device. The Demo Service Light provides the same actions as the Demo Service except those related to the digit recognition. It doesn't contain Tensorflow and runs as a standalone application.

.Running the REST API Demo Service Light in Docker on Raspberry Pi
[source,bash,subs="verbatim,attributes"]
----
docker run --name sponge-demo-lite -d --restart always --network=host openksavi/sponge-demo-lite -Dsponge.restApiServer.serviceDiscoveryUrl="http://$(hostname -I | awk '{print $1}'):1836"
----

The default port `1836` is used by the REST API and the port `1837` is used by the gRPC API.

.Verification
[source,bash,subs="verbatim,attributes"]
----
curl http://localhost:1836/version
----

[discrete]
=== Setting up manually and deploying in Tomcat
First, you have to create the web application and {sponge} scripts.
[source,bash,subs="verbatim,attributes"]
----
cd sponge-examples-projects/sponge-examples-project-demo-service
mvn clean install -Pall
----

The resulting archive `target/sponge-demo-api.war` is the web application providing the Demo REST API service. The archive `target/sponge-scripts.zip` contains Sponge script files and the Digits recognition example files (see the TensorFlow integration chapter) that will be accessed by the web application.

Assuming that Tomcat is installed in `/opt/tomcat` and the Sponge script files and the Digits recognition example files are extracted into the `/opt/tomcat/sponge` directory, you should add the following properties to the `catalina.properties` file:
----
sponge.home=/opt/tomcat/sponge
digits.home=/opt/tomcat/sponge/digits
password.file=/opt/tomcat/sponge/password.txt
sponge.grpc.port=8081
----

The sample file `password.txt` contains the hashed, insecure password `password` for the user `admin`. The user `admin` has access to more actions that the _anonymous_ user. This simple password can be used only for development and tests. In the case of publishing the service, this file should contain the hashed, secret and strong password.

[source,bash]
----
# Create the password file.
sudo echo -n username-password | shasum -a 512 | awk '{ print $1 }' > /opt/tomcat/sponge/password.txt

# Setup privileges.
cd /opt/tomcat
sudo chown -R tomcat:tomcat sponge

# Restart Tomcat.
sudo systemctl restart tomcat.service
----

Deploy the web application as `sponge-demo-api` using the Tomcat Web Application Manager. Then test the service.

[source,bash]
----
curl -i -k -X POST -H "Content-type:application/json" http://localhost:8080/version
----

[discrete]
=== Running in Jetty
You may also run this example using the Jetty server started by the maven command:

.Example of the REST API servlet
[source,bash,subs="verbatim,attributes"]
----
cd sponge-examples-projects/sponge-examples-project-demo-service
mvn jetty:run
----

[[iot-rpi-service]]
== IoT on Raspberry Pi project
The {sourcesUrl}/sponge-examples-projects/sponge-examples-project-iot-rpi[IoT on Raspberry Pi] project shows how to use {sponge} to read sensors, set actuators, take pictures, send SMS messages, send emails and execute OS commands.

The {sponge} standalone command line application is installed on a Raspberry Pi with a GrovePi extension board. {sponge} provides a synchronous REST API to remotely call actions (that for example change state of actuators). It also sends sensor data (temperature, humidity and light) to an MQTT broker using Apache Camel. The project allows processing sensor data on two levels: locally on the Raspberry Pi edge device by {sponge} (to avoid sending too much data to a management system) or by an external system that connects to the MQTT broker.

[discrete]
=== The hardware

.The sensors and actuators connected to the GrovePi
[cols="2,3"]
|===
|Sensor / actuator |Description

|http://wiki.seeedstudio.com/Grove-TemperatureAndHumidity_Sensor/[DHT sensor] |Connected to the port D2.
|https://www.seeedstudio.com/Grove-Light-Sensor-p-746.html[Light sensor] |Connected to the port A1.
|http://wiki.seeedstudio.com/Grove-Rotary_Angle_Sensor/[Rotary angle sensor] |Connected to the port A0.
|http://wiki.seeedstudio.com/Grove-Sound_Sensor/[Sound sensor] |Connected to the port A2.
|http://wiki.seeedstudio.com/Grove-Red_LED/[Red LED] |Connected to the port D4.
|https://www.seeedstudio.com/Grove-Blue-LED-p-1139.html[Blue LED] |Connected to the port D5.
|http://wiki.seeedstudio.com/Grove-Buzzer/[Buzzer] |Connected to the port D7.
|http://wiki.seeedstudio.com/Grove-LCD_RGB_Backlight/[LCD RGB Backlight] |Connected to the port I2C-1.
|===

.Other hardware connected to the Raspberry Pi
[cols="2,3"]
|===
|Name |Description

|HD Night Vision IR camera |
|Huawei E3131h-2 modem |Connected via a powered USB hub.
|===

[discrete]
=== Prerequisites
The Linux distribution used for this example is Raspbian. All command are invoked by the user `pi`. For SMS sending the `gammu` utility should be installed.

[source,bash]
----
$ sudo apt-get install gammu
----

[discrete]
=== Installation
First you should download and unpack the {sponge} standalone command line application into the `/home/pi/local/app/` directory. The directory `/home/pi/local/app/examples/sponge-iot-rpi` (containing the example knowledge base files) should be copied to `/home/pi/local/` in order to modify the configuration files in a fresh copy.

The preferred installation is as a systemd service.

[source,bash]
----
$ sudo vim /lib/systemd/system/sponge_iot.service
----

[source,bash,subs="verbatim,attributes"]
----
[Unit]
Description=Sponge IoT Service
After=multi-user.target

[Service]
Type=simple
ExecStart=/bin/bash /home/pi/local/app/sponge-{projectVersion}/bin/sponge -c /home/pi/local/sponge-iot-rpi/kb/sponge_iot.xml -Dsponge.home=/home/pi/local/sponge-iot-rpi
WorkingDirectory=/home/pi/local/sponge-iot-rpi/
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
----

[source,bash]
----
$ sudo chmod 644 /lib/systemd/system/sponge_iot.service
$ sudo systemctl daemon-reload
$ sudo systemctl enable sponge_iot.service
----

[discrete]
=== Configuration
The `sponge_iot.properties` file allows the configuration of the service name, the phone number that will receive SMS notifications, the email address for notifications, the temperature threshold to trigger sending an SMS notification, the email client settings and the MQTT broker settings.

Note that the provided password file `password.txt` stores sample passwords. For each user the password is: password.

[discrete]
=== REST API Actions
The subset of {sponge} actions is published via the {sponge} REST API. The published actions have their metadata configured. These actions could be used by the {sponge} mobile client application to manage the IoT device using a GUI.

.The published actions
[cols="1,4"]
|===
|Name |Description

|SetGrovePiMode |Sets the GrovePi mode (`auto` or `manual`). In the `auto` mode the device behavior is automated according to the following rules. The LCD display shows the current temperature and humidity. The red LED is turned on if there is dark in the room. The blue LED light depends on the position of the rotary angle sensor. The `auto` mode is implemented by triggers and correlators. In the `manual` mode the actuators (LCD, LEDs, etc.) can be managed manually via the published actions.

|ManageLcd |Provides management of the LCD properties, i.e. the display text and color.

|ManageSensorActuatorValues |Provides management of the sensor and actuator values. Reads the temperature and humidity sensor, the light sensor, the rotary angle sensor and the sound sensor. Sets the values of the LEDs and the buzzer.

|TakePicture |Takes a picture using the RPI camera.

|SendNotificationEmail |Sends a notification email to the configured recipient.

|SendNotificationSms |Sends a notification SMS to the configured recipient.

|OsGetDiskSpaceInfo |Executes `df -h` and returns the disk space info as a markdown string.

|OsDmesg |Executes `dmesg` and returns the output as a markdown string.
|===

The REST API uses <<rest-api-server-simple-security-strategy,the simple security strategy>>.

[discrete]
=== MQTT
{sponge} publishes the values of temperature, humidity and light sensors to the MQTT topics `sponge/temperature`, `sponge/humidity` and `sponge/light`. The topic prefix can be changed in the configuration.

[discrete]
=== Modifications in the knowledge bases
After installation, configuration and an initial run you could add your modifications to the knowledge bases. The preferred way to do this is:

* Temporarily stop and disable the {sponge} system service.
* Run {sponge} in an interactive mode in the current console.

[source,bash,subs="verbatim,attributes"]
----
$ cd ~/local/sponge-iot-rpi
$ sudo ~/local/app/sponge-{projectVersion}/bin/sponge -c ~/local/sponge-iot-rpi/kb/sponge_iot.xml -Dsponge.home=. -i iot
----

* Open a new shell console to view logs.

[source,bash,subs="verbatim,attributes"]
----
$ tail -f ~/local/sponge-iot-rpi/logs/sponge-<current_date>.log
----

* Open a new shell console to modify and save the knowledge base files.
* After saving the knowledge base files, reload the knowledge bases in the interactive mode.

[source,bash,subs="verbatim,attributes"]
----
 > sponge.reload()
----

* If the changes require restarting {sponge}, exit the interactive mode (it stops the {sponge} engine) and start {sponge} again.

[source,bash,subs="verbatim,attributes"]
----
 > exit
 $ sudo ~/local/app/sponge-{projectVersion}/bin/sponge -c ~/local/sponge-iot-rpi/kb/sponge_iot.xml -Dsponge.home=. -i iot
----

* If you modify actions and use the {sponge} mobile client application to test the knowledge bases, please remember to refresh the action metadata in the GUI.
* Repeat these steps until your knowledge bases are finished.
* Start and enable the {sponge} system service.

[[mpd-mpc-raspberry]]
== MPD client service project
The {sponge} MPD client service provides a basic set of Music Player Demon (MPD) client related actions. It can be used in combination with the generic {sponge} mobile client application as a simple music player.

The {sponge} MPD service uses the `mpc` client commandline to communicate with the MPD server. For performance reasons the {sponge} MPD service should be installed on the same machine that runs an MPD server.

NOTE: One of the aims of the {sponge} MPD client service example is to showcase the ability of {sponge} to publish a set of commandline tool invocations as a REST API and use it in a mobile application. It is not a replacement for existing MPD clients available for mobile devices because they connect to an MPD server directly. The architecture shown in this example introduces an additional layer between the MPD server and the GUI MPD client (in that case the generic {sponge} mobile client application) that can have a noticable impact on the performance.

[discrete]
=== Running in Docker
The Docker image `openksavi/sponge-mpd` contains a predefined {sponge} MPD service.

The main use case is that the service runs in Docker on a Raspberry PI with an already configured MPD. There is a number of Linux distributions for a Raspberry PI that provide well configured music player features. For this example https://volumio.org[Volumio] has been chosen.

The architecture of this solution is: Raspberry PI with the MPD server (Volumio) and Docker containing the {sponge} MPD service.

Installing the {sponge} MPD service:

* https://volumio.org/get-started/[Download], install and configure Volumio for Raspberry PI.
* Enable https://volumio.github.io/docs/User_Manual/SSH.html[SSH].
* Connect to the Raspberry PI via SSH as the `volumio` user.
* Install and configure https://howchoo.com/g/nmrlzmq1ymn/how-to-install-docker-on-your-raspberry-pi[Docker].

----
sudo curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
sudo usermod -aG docker volumio
----

* Run the {sponge} MPD service in Docker.

----
docker pull openksavi/sponge-mpd
docker run --name sponge-mpd -d --restart always --network=host openksavi/sponge-mpd -Dsponge.restApiServer.serviceDiscoveryUrl="http://$(hostname -I | awk '{print $1}'):1836"
----

Setting the `sponge.restApiServer.serviceDiscoveryUrl` property allows client applications (e.g. the Sponge Remote mobile application) to automatically find this service in a local network. If you want to change the service name, provide the `sponge.restApiServer.name` property as well, e.g. `-Dsponge.restApiServer.name="Docker MPD"`.

* Check the {sponge} MPD service logs.

----
docker logs sponge-mpd -f
----

Limitations:

* The MPD connection configuration (e.g. the MPD host) is not persisted between restarts.
* This Docker image has been tested only on a Linux host.

== Scripting examples
The scripting examples show how to use certain {sponge} functionalities in script knowledge bases. See the sources in {sourcesUrl}/sponge-jython/examples/script/py[Python examples], {sourcesUrl}/sponge-jruby/examples/script/rb[Ruby examples], {sourcesUrl}/sponge-groovy/examples/script/groovy[Groovy examples] and {sourcesUrl}/sponge-nashorn/examples/script/js[JavaScript examples].

Each of these examples is also used in the corresponding JUnit class as a test case with assertions. Note that not all of these examples will work in the standalone application because some of them require additional setup.

.Scripting examples
[cols="1,3"]
|===
|Name |Description

|`actions`
ifdef::useReferences[({pySourcesUrl}/actions.py[py], {rbSourcesUrl}/actions.rb[rb], {groovySourcesUrl}/actions.groovy[groovy], {jsSourcesUrl}/actions.js[js])]
|Shows how to use actions.

|`correlators`
ifdef::useReferences[({pySourcesUrl}/correlators.py[py], {rbSourcesUrl}/correlators.rb[rb], {groovySourcesUrl}/correlators.groovy[groovy], {jsSourcesUrl}/correlators.js[js])]
|Shows how to use correlators. The correlator creates an event log - a list of events that it listens to.

|`correlators_duration`
ifdef::useReferences[({pySourcesUrl}/correlators_duration.py[py], {rbSourcesUrl}/correlators_duration.rb[rb], {groovySourcesUrl}/correlators_duration.groovy[groovy], {jsSourcesUrl}/correlators_duration.js[js])]
|Shows how to use correlators with duration.

|`events_clone_policy`
ifdef::useReferences[({pySourcesUrl}/events_clone_policy.py[py], {rbSourcesUrl}/events_clone_policy.rb[rb], {groovySourcesUrl}/events_clone_policy.groovy[groovy], {jsSourcesUrl}/events_clone_policy.js[js], {pySourcesUrl}/events_clone_policy.xml[XML configuration])]
|Shows event clone policies.

|`events_cron`
ifdef::useReferences[({pySourcesUrl}/events_cron.py[py], {rbSourcesUrl}/events_cron.rb[rb], {groovySourcesUrl}/events_cron.groovy[groovy], {jsSourcesUrl}/events_cron.js[js])]
|Shows sending events using Cron.

|`events_removing`
ifdef::useReferences[({pySourcesUrl}/events_removing.py[py], {rbSourcesUrl}/events_removing.rb[rb], {groovySourcesUrl}/events_removing.groovy[groovy], {jsSourcesUrl}/events_removing.js[js])]
|Shows how to remove scheduled events.

|`filters_deduplication`
ifdef::useReferences[({pySourcesUrl}/filters_deduplication.py[py], {rbSourcesUrl}/filters_deduplication.rb[rb], {groovySourcesUrl}/filters_deduplication.groovy[groovy], {jsSourcesUrl}/filters_deduplication.js[js])]
|Shows how to use a deduplication filter to prevent from processing many events that carry the same information.

|`filters_java`
ifdef::useReferences[({pySourcesUrl}/filters_java.py[py], {rbSourcesUrl}/filters_java.rb[rb], {groovySourcesUrl}/filters_java.groovy[groovy], {jsSourcesUrl}/filters_java.js[js])]
|Shows how to use a Java-based filter.

|`filters`
ifdef::useReferences[({pySourcesUrl}/filters.py[py], {rbSourcesUrl}/filters.rb[rb], {groovySourcesUrl}/filters.groovy[groovy], {jsSourcesUrl}/filters.js[js])]
|Shows how to use script-based filters.

|`actions_hello_world`
ifdef::useReferences[({pySourcesUrl}/actions_hello_world.py[py], {rbSourcesUrl}/actions_hello_world.rb[rb], <{groovySourcesUrl}/actions_hello_world.groovy[groovy], {jsSourcesUrl}/actions_hello_world.js[js], {pySourcesUrl}/actions_hello_world.xml[XML configuration])]
|Hello world action complete example.

|`triggers_hello_world`
ifdef::useReferences[({pySourcesUrl}/triggers_hello_world.py[py], {rbSourcesUrl}/triggers_hello_world.rb[rb], <{groovySourcesUrl}/triggers_hello_world.groovy[groovy], {jsSourcesUrl}/triggers_hello_world.js[js], {pySourcesUrl}/triggers_hello_world.xml[XML configuration])]
|Hello world trigger complete example.

|`knowledge_base_callbacks`
ifdef::useReferences[({pySourcesUrl}/knowledge_base_callbacks.py[py], {rbSourcesUrl}/knowledge_base_callbacks.rb[rb], {groovySourcesUrl}/knowledge_base_callbacks.groovy[groovy], {jsSourcesUrl}/knowledge_base_callbacks.js[js])]
|Shows how to use knowledge base callback functions.

|`knowledge_base_load`
ifdef::useReferences[({pySourcesUrl}/knowledge_base_load.py[py], {rbSourcesUrl}/knowledge_base_load.rb[rb], {groovySourcesUrl}/knowledge_base_load.groovy[groovy], {jsSourcesUrl}/knowledge_base_load.js[js])]
|Shows how to load an additional knowledge base file.

|`knowledge_base_manager`
ifdef::useReferences[({pySourcesUrl}/knowledge_base_manager.py[py], {rbSourcesUrl}/knowledge_base_manager.rb[rb], {groovySourcesUrl}/knowledge_base_manager.groovy[groovy], {jsSourcesUrl}/knowledge_base_manager.js[js])]
|Shows knowledge base operations.

|`library`
ifdef::useReferences[({pySourcesUrl}/library.py[py], {rbSourcesUrl}/library.rb[rb], {groovySourcesUrl}/library.groovy[groovy], {jsSourcesUrl}/library.js[js], {pySourcesUrl}/library.xml[XML configuration])]
|Shows how to use a scripting language specific library (e.g. `httplib` for Python) to check HTTPS host status.

|`plugins_java`
ifdef::useReferences[({pySourcesUrl}/plugins_java.py[py], {rbSourcesUrl}/plugins_java.rb[rb], {groovySourcesUrl}/plugins_java.groovy[groovy], {jsSourcesUrl}/plugins_java.js[js], {pySourcesUrl}/plugins_java.xml[XML configuration])]
|Shows how to define and use a Java-based plugin.

|`plugins_kb`
ifdef::useReferences[({pySourcesUrl}/plugins_kb.py[py], {rbSourcesUrl}/plugins_kb.rb[rb], {groovySourcesUrl}/plugins_kb.groovy[groovy], {jsSourcesUrl}/plugins_kb.js[js], {pySourcesUrl}/plugins_kb.xml[XML configuration])]
|Shows how to define and use a script-based plugin.

|`rules`
ifdef::useReferences[({pySourcesUrl}/rules.py[py], {rbSourcesUrl}/rules.rb[rb], {groovySourcesUrl}/rules.groovy[groovy], {jsSourcesUrl}/rules.js[js])]
|Shows how to define and use ordered rules, i.e. rules listening to ordered sequences of events. Event conditions are specified using lambda expressions as well as class methods.

|`rules_events`
ifdef::useReferences[({pySourcesUrl}/rules_events.py[py], {rbSourcesUrl}/rules_events.rb[rb], {groovySourcesUrl}/rules_events.groovy[groovy], {jsSourcesUrl}/rules_events.js[js], {pySourcesUrl}/rules_events.xml[XML configuration])]
|Shows how to define and use rules that have different event modes, durations etc.

|`rules_heartbeat`
ifdef::useReferences[({pySourcesUrl}/rules_heartbeat.py[py], {rbSourcesUrl}/rules_heartbeat.rb[rb], {groovySourcesUrl}/rules_heartbeat.groovy[groovy], {jsSourcesUrl}/rules_heartbeat.js[js])]
|Heartbeat complete example.

|`rules_none_mode_events_conditions`
ifdef::useReferences[({pySourcesUrl}/rules_none_mode_events_conditions.py[py], {rbSourcesUrl}/rules_none_mode_events_conditions.rb[rb], {groovySourcesUrl}/rules_none_mode_events_conditions.groovy[groovy], {jsSourcesUrl}/rules_none_mode_events_conditions.js[js])]
|Shows how to define and use rules that have `none` event mode and event conditions.

|`rules_none_mode_events`
ifdef::useReferences[({pySourcesUrl}/rules_none_mode_events.py[py], {rbSourcesUrl}/rules_none_mode_events.rb[rb], {groovySourcesUrl}/rules_none_mode_events.groovy[groovy], {jsSourcesUrl}/rules_none_mode_events.js[js])]
|Shows how to define and use rules that have `none` event mode.

|`unordered_rules`
ifdef::useReferences[({pySourcesUrl}/unordered_rules.py[py], {rbSourcesUrl}/unordered_rules.rb[rb], {groovySourcesUrl}/unordered_rules.groovy[groovy], {jsSourcesUrl}/unordered_rules.js[js])]
|Shows how to define and use unordered rules, i.e. rules listening to unordered sequences of events. Event conditions are specified using lambda expressions as well as class methods.

|`triggers`
ifdef::useReferences[({pySourcesUrl}/triggers.py[py], {rbSourcesUrl}/triggers.rb[rb], {groovySourcesUrl}/triggers.groovy[groovy], {jsSourcesUrl}/triggers.js[js], {pySourcesUrl}/triggers.xml[XML configuration])]
|Shows how to define and use triggers.

|`triggers_event_pattern`
ifdef::useReferences[({pySourcesUrl}/triggers_event_pattern.py[py], {rbSourcesUrl}/triggers_event_pattern.rb[rb], {groovySourcesUrl}/triggers_event_pattern.groovy[groovy], {jsSourcesUrl}/triggers_event_pattern.js[js])]
|Shows how to define and use triggers that specify events they listen to as a pattern based on a regular expression.
|===

== Functionality examples
The features examples show how to use some of {sponge} functionalities. They are not implemented in all supported scripting languages.

.Features examples
[cols="1,3"]
|===
|Name |Description

|`fibonacci`
ifdef::useReferences[({coreSourcesUrl}/fibonacci.py[py])]
|Shows how to send a chain of events, each carrying a Fibonacci number as an attribute.

|`engine_parameters`
ifdef::useReferences[({coreSourcesUrl}/engine_parameters.xml[xml])]
|Shows how to set engine parameters in the XML configuration file.

|`event_pattern`
ifdef::useReferences[({coreSourcesUrl}/event_pattern.py[py])]
|Shows how to use event name patterns and how to enable/disable processors manually.

|`spring`
ifdef::useReferences[({springSourcesUrl}/spring.py[py], {sourcesUrl}/sponge-spring/src/test/java/org/openksavi/sponge/spring/test/SpringTest.java[java])]
|Shows how to integrate with Spring framework.

|`camel_producer`
ifdef::useReferences[({camelSourcesUrl}/camel_producer.py[py], {sourcesUrl}/sponge-camel/src/test/java/org/openksavi/sponge/camel/test/SimpleCamelProducerTest.java[java])]
|Shows how to handle messages coming from Apache Camel route by a {sponge} trigger.

|`camel_consumer`
ifdef::useReferences[({camelSourcesUrl}/camel_consumer.py[py], {sourcesUrl}/sponge-camel/src/test/java/org/openksavi/sponge/camel/test/SimpleCamelConsumerTest.java[java])]
|Shows how to handle messages coming from {sponge} by an Apache Camel route.

|`camel_rss`
ifdef::useReferences[({camelSourcesUrl}/camel_rss.py[py], {sourcesUrl}/sponge-camel/src/test/java/org/openksavi/sponge/camel/test/CamelRssTest.java[java])]
|Shows how to integrate with Apache Camel to send and handle {sponge} events based on RSS feeds. This example uses a Spring configuration.

|`camel_producer_overridden_action`
ifdef::useReferences[({camelSourcesUrl}/camel_producer_overridden_action.py[py], {sourcesUrl}/sponge-camel/src/test/java/org/openksavi/sponge/camel/test/CamelProducerOverriddenActionTest.java[java])]
|Shows how to handle messages coming from Apache Camel route by a {sponge} trigger using an overridden Camel producer action.

|`camel_producer_custom_action`
ifdef::useReferences[({camelSourcesUrl}/camel_producer_custom_action.py[py], {sourcesUrl}/sponge-camel/src/test/java/org/openksavi/sponge/camel/test/CamelProducerCustomActionTest.java[java])]
|Shows how to handle messages coming from Apache Camel route by a {sponge} trigger using a custom Camel producer action.

|`camel_multiple_consumer`
ifdef::useReferences[({camelSourcesUrl}/camel_multiple_consumer.py[py], {sourcesUrl}/sponge-camel/src/test/java/org/openksavi/sponge/camel/test/CamelMultipleConsumerTest.java[java])]
|Shows sending Camel messages to many endpoints in a single {sponge} trigger.

|`py4j_java_server`
ifdef::useReferences[({py4jSourcesUrl}/java_server/py4j_java_server_python_hello_world.py[cpython], {py4jSourcesUrl}/java_server/py4j_java_server_sponge_hello_world.xml[xml], {py4jSourcesUrl}/java_server/py4j_java_server_sponge_hello_world.py[jython])]
|Shows how to integrate with CPython program using Py4J - Java server.

|`py4j_python_server`
ifdef::useReferences[({py4jSourcesUrl}/python_server/py4j_python_server_python_hello_world.py[cpython], {py4jSourcesUrl}/python_server/py4j_python_server_sponge_hello_world.xml[xml], {py4jSourcesUrl}/python_server/py4j_python_server_sponge_hello_world.py[jython], {sourcesUrl}/sponge-py4j/src/test/java/org/openksavi/sponge/py4j/PythonService.java[java])]
|Shows how to integrate with CPython program using Py4J - Python server.

|`py4j_java_server_tls`
ifdef::useReferences[({py4jSourcesUrl}/java_server_tls/py4j_java_server_tls_python_hello_world.py[cpython], {py4jSourcesUrl}/java_server_tls/py4j_java_server_tls_sponge_hello_world.xml[xml], {py4jSourcesUrl}/java_server_tls/py4j_java_server_tls_sponge_hello_world.py[jython])]
|Shows how to integrate with CPython program using Py4J - Java server with TLS security.

|`midi_generate_sound`
ifdef::useReferences[({midiSourcesUrl}/midi_generate_sound.py[py])]
|Shows how to generate MIDI sounds in a {sponge} knowledge base.

|`midi_input`
ifdef::useReferences[({midiSourcesUrl}/midi_input.py[py])]
|Shows how to process MIDI messages created by an external MIDI input device.

|`midi_play_file`
ifdef::useReferences[({midiSourcesUrl}/midi_play_file.py[py])]
|Shows how MIDI messages created by a MIDI sequencer playing a MIDI file could be processed in a {sponge} knowledge base.
|===

== Standalone examples
The standalone examples show how to use some of {sponge} features in the standalone command-line application.

.Standalone examples
[cols="1,3"]
|===
|Name |Description

|`standalone_news`
ifdef::useReferences[({sourcesUrl}/sponge-standalone/examples/standalone/news[sources])]
|This example is based on complete example project of embedding {sponge} - News, but adjusted to a standalone version.

|`standalone_camel_rss_news`
ifdef::useReferences[({sourcesUrl}/sponge-standalone/examples/standalone/camel_rss_news[sources])]
|This example is based on complete example project of embedding {sponge} - Camel RSS News, but adjusted to a standalone version.

|`camel_route_groovy`
ifdef::useReferences[({sourcesUrl}/sponge-examples-projects/sponge-examples-project-standalone-camel-groovy[sources])]
|Camel routes in Groovy Spring configuration.

|`camel_route_xml`
ifdef::useReferences[({sourcesUrl}/sponge-examples-projects/sponge-examples-project-standalone-camel-xml[sources])]
|Camel context and routes in XML Spring configuration.
|===
