= {sponge} gRPC API client for Dart
The {sponge} gRPC API client for Dart simplifies connecting to a remote {sponge} gRPC API service from applications written in Dart.

.gRPC API client example
[source,dart]
----
import 'package:grpc/grpc.dart';
import 'package:sponge_client_dart/sponge_client_dart.dart';
import 'package:sponge_grpc_client_dart/sponge_grpc_client_dart.dart';

void main() async {
  // Create a new Sponge Remote API client.
  var spongeClient = SpongeClient(
      SpongeClientConfiguration('http://localhost:8888'));

  // Create a new Sponge gRPC API client associated with the Remote API client.
  // Don't use insecure channel in production.
  var grpcClient = DefaultSpongeGrpcClient(spongeClient,
      channelOptions:
          ChannelOptions(credentials: const ChannelCredentials.insecure()));

  // Get the Sponge Remote API version.
  var version = await grpcClient.getVersion();

  print('Version: $version');

  // Close the client connection.
  await grpcClient.close();
}
----

The client follows the convention that a gRPC service port is a Remote API port plus `1`. If the gRPC service uses a different port, set this port in the client configuration.

.Setting port in a gRPC API client
[source,dart]
----
DefaultSpongeGrpcClient(spongeClient,
  configuration: SpongeGrpcClientConfiguration(port: 9000),
  channelOptions: ChannelOptions(credentials: const ChannelCredentials.insecure()));
----

This project uses the https://pub.dev/packages/grpc[Dart implementation of gRPC].

The `DefaultSpongeGrpcClient` doesn't support a web platform.

To use a {sponge} gRPC API client in a web client you have to instantiate `WebSpongeGrpcClient` instead of `DefaultSpongeGrpcClient` and import `package:sponge_grpc_client_dart/sponge_grpc_client_dart_web.dart`.

Unless noted otherwise in the release notes, versions of the gRPC API client for Dart that have the same `major.minor` numbers as the {sponge} service are compatible.

The gRPC API client for Dart is published as `sponge_grpc_client_dart` at https://pub.dartlang.org/packages/sponge_grpc_client_dart[pub.dartlang.org].
