= {sponge} REST API client for Java
The {sponge} REST API client for Java simplifies connecting to a remote {sponge} REST API server from applications written in Java. The default implementation uses the http://square.github.io/okhttp/[OkHttp] library.

.REST API client for an anonymous user
[source,java]
----
try (SpongeRestApiClient client = new DefaultSpongeRestApiClient(RestApiClientConfiguration.builder()
        .url(String.format("http://localhost:%d/%s", PORT, RestApiConstants.DEFAULT_PATH))
        .build())) { // <1>
    String upperCaseText = client.call(String.class, "UpperCase", "text"); // <2>
}
----
<1> Create a new REST API client.
<2> Call the remote action.

.REST API client for a named user
[source,java]
----
SpongeRestApiClient client = new DefaultSpongeRestApiClient(RestApiClientConfiguration.builder()
        .url(String.format("http://localhost:%d/%s", PORT, RestApiConstants.DEFAULT_PATH))
        .username(username)
        .password(password)
        .build());
----

`DefaultSpongeRestApiClient` performs best when you create a single `DefaultSpongeRestApiClient` instance and reuse it for all of your REST API calls.

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/restapi/client/DefaultSpongeRestApiClient.html[`DefaultSpongeRestApiClient` Javadoc] and examples in the source code.

There is also the implementation that uses the Spring (version 5) RestTemplate: `SpringSpongeRestApiClient`.

== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-rest-api-client</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

In case of using `SpringSpongeRestApiClient` you should also add the following dependency to your `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-http</artifactId>
</dependency>
----
