= Integration

== Spring framework
{sponge} engine can be configured as a Spring bean. That configuration provides standardized access to an embedded {sponge} engine for example in J2EE environment.

To provide access to the Spring `ApplicationContext` in the knowledge base, the `SpringPlugin` instance should be created, *configured as a Spring bean and added to the {sponge} engine*. The Spring plugin shouldn't be defined in {sponge} XML configuration file.

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/spring/SpringPlugin.html[`SpringPlugin` Javadoc].

.Spring Java configuration example
[source,java]
----
@Configuration
public class TestConfig {

    @Bean
    public Engine spongeEngine() { // <1>
        return SpringSpongeEngine.builder().plugin(springPlugin()).knowledgeBase("kb", "examples/spring/spring.py").build(); // <2>
    }

    @Bean
    public SpringPlugin springPlugin() { // <3>
        return new SpringPlugin();
    }

    @Bean
    public String testBean() {
        return BEAN_VALUE;
    }
}
----
<1> The engine configured as the Spring bean. The `SpringSpongeEngine` implementation is used here in order to startup and shutdown the engine by Spring. `DefaultSpongeEngine` could also be used here but it wouldn't provide automatic startup and shutdown.
<2> Added `SpringPlugin`.
<3> `SpringPlugin` configured as the Spring bean.

.Python knowledge base
[source,python]
----
class SpringTrigger(Trigger):
    def onConfigure(self):
        self.withEvent("springEvent")
    def onRun(self, event):
        beanValue = spring.context.getBean("testBean") # <1>
        self.logger.debug("Bean value = {}", beanValue)
----
<1> A Spring bean named `"testBean"` is acquired from the Spring `ApplicationContext` by using `SpringPlugin` instance referenced by the `spring` variable.

The `SpringSpongeEngine` starts up automatically (in the `afterPropertiesSet` Spring callback method) by default. However it can be configured not to start automatically by setting `autoStartup` to `false`.

.SpringSpongeEngine not starting automatically example
[source,java]
----
@Bean
public SpongeEngine spongeEngine() {
    return SpringSpongeEngine.builder().autoStartup(false).plugin(springPlugin()).knowledgeBase("kb", "examples/spring/spring.py").build();
}
----

[discrete]
=== Maven configuration
Maven users will need to add the following dependency to their `pom.xml` for this component:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-spring</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

include::user-guide-integration-camel.adoc[leveloffset=+1]

include::user-guide-integration-remote-api.adoc[leveloffset=+1]

include::user-guide-integration-remote-api-server.adoc[leveloffset=+1]

include::user-guide-integration-remote-api-client-java.adoc[leveloffset=+1]

include::user-guide-integration-remote-api-client-dart.adoc[leveloffset=+1]

include::user-guide-integration-grpc-api.adoc[leveloffset=+1]

include::user-guide-integration-grpc-api-server.adoc[leveloffset=+1]

include::user-guide-integration-grpc-api-client-java.adoc[leveloffset=+1]

include::user-guide-integration-grpc-api-client-dart.adoc[leveloffset=+1]

[[integration-external-subprocess]]
== Running external processes
{sponge} provides the `ProcessInstance` API to run an external executable as a subprocess of the {sponge} Java process. This feature is used by some of the plugins, for example by the Py4J integration plugin to execute an external Python script.

In general, an external process can be executed using:

* {sponge} `ProcessInstance` API (covered in this chapter),
* scripting language API,
* Apache Camel http://camel.apache.org/exec.html[exec component],
* Java API (`ProcessBuilder`).

.Subprocess configuration parameters
[cols="1,1,4"]
|===
|Name |Type |Description

|`name`
|`String`
|The process name.

|`executable`
|`String`
|The process executable.

|`argument`
|`String`
|Zero or more process arguments.

|`workingDir`
|`String`
|The process working directory. If `null` (the default value) then the current directory will be used.

|`env`
|name, value
|Zero or more additional environment variables for the subprocess.

|`waitSeconds`
|`Long`
|The maximum number of seconds to wait after the start of the process. The thread that started the process will be blocked until the time elapses or the subprocess exits. If `null` (the default value), the thread will not wait.

|`inputRedirect`
|`InputRedirect`
|The standard input redirect type (see the following tables). There are convenience methods `inputAs...` available.

|`outputRedirect`
|`OutputRedirect`
|The standard output redirect type (see the following tables). There are convenience methods `outputAs...` available.

|`errorRedirect`
|`ErrorRedirect`
|The standard error redirect type (see the following tables). There are convenience methods `errorAs...` available.

|`charset`
|`String`
|The the charset of the subprocess streams used if the redirect type is `STRING`.

|`waitForPositiveLineRegexp`
|`String`
|The Java regular expression of a line from the process output text stream. The thread that started the process will wait (blocking) for such line. If set to `null`, the thread will not wait for a specific line (or `waitForNegativeLineRegexp` if set).

|`waitForNegativeLineRegexp`
|`String`
|Sets the Java regular expression of a line from the process output text stream that signals an error and should cause throwing an exception.

|`waitForLineTimeout`
|`Long`
|The timeout for waiting for a specific line from the process output stream (in seconds). If `null`, the thread could wait indefinitely. If the timeout is exceeded, the exception will be thrown.

|`inputString`
|`String`
|The input string that will be set as the process standard input. Applicable only if the input redirect type is STRING.

|`inputBinary`
|`byte[]`
|he input bytes that will be set as the process standard input. Applicable only if the input redirect type is BINARY.
|===

.Standard input redirect type
[cols="1,5"]
|===
|Value |Description

|`PIPE` |Indicates that subprocess standard input will be connected to the current Java process over a pipe. This is the default handling of subprocess standard input.

|`INHERIT` |Sets the destination for subprocess standard input to be the same as those of the current Java process.

|`STRING` |Sets the subprocess input as the `ProcessConfiguration.inputString` string.

|`BINARY` |Sets the subprocess input as the `ProcessConfiguration.inputBinary` bytes.

|`FILE` |Sets the subprocess input as the `ProcessConfiguration.inputFile` file specified as the filename.

|`STREAM` |Sets the subprocess input as a stream. This is a special case of `PIPE` that makes easier writing to and closing the subprocess standard input `ProcessInstance.getInput()` after start. Then you should invoke manually `ProcessInstance.waitForReady()`.
|===

.Standard output redirect type
[cols="1,5"]
|===
|Value |Description

|`PIPE` |Indicates that subprocess standard output will be connected to the current Java process over a pipe. This is the default handling of subprocess standard output.

|`INHERIT` |Sets the destination for subprocess standard output to be the same as those of the current Java process.

|`STRING` |Writes all subprocess standard output to the `ProcessInstance.outputString` string. The thread that started the subprocess will wait for the subprocess to exit.

|`BINARY` |Writes all subprocess standard output to the `ProcessInstance.outputBinary` byte array. The thread that started the subprocess will wait for the subprocess to exit.

|`FILE` |Writes all subprocess standard output to the `ProcessInstance.outputFile` file. The thread that started the subprocess will wait for the subprocess to exit.

|`CONSUMER` |Sends a subprocess standard output as text lines to a line consumer (if set). It also logs the subprocess standard output to the logger (as INFO).
|===

.Standard error redirect type
[cols="1,5"]
|===
|Value |Description

|`PIPE` |Indicates that subprocess error output will be connected to the current Java process over a pipe. This is the default handling of subprocess error output.

|`INHERIT` |Sets the destination for subprocess error output to be the same as those of the current Java process.

|`STRING` |Writes all subprocess error output to the `ProcessInstance.errorString` string. The thread that started the subprocess will wait for the subprocess to exit.

|`FILE` |Writes all subprocess error output to the `ProcessInstance.getErrorFile` file. The thread that started the subprocess will wait for the subprocess to exit.

|`EXCEPTION` |Throw an exception if the error output is not empty. The thread that started the subprocess will wait for the subprocess to exit.

|`CONSUMER` |Sends a subprocess standard error as text lines to a line consumer (if set). It also logs the subprocess error output to the logger (as WARN).
|===

The preferred way to configure redirects is to use `inputAs...`, `outputAs...` and `errorAs...` methods.

In order to run a new process you have to create a process instance builder by invoking `sponge.process()`. Then you can run a new process:

* Synchronously by invoking the `run()` method. The current thread waits for the process exit.
* Asynchronously by invoking the `runAsync()` method. The current thread waits for the process exit only if necessary (in compliance with the process configuration).

.Example of running an external executable with arguments in Java
[source,java]
----
ProcessInstance process = engine.getOperations().process("echo", "TEST").outputAsString().run();
String output = process.getOutputString();
----

.Example of running an external executable with arguments in Python
[source,python]
----
process = sponge.process("echo", "TEST").outputAsString().run()
print process.outputString
----

.Example of running an external executable with an additional environment in Java
[source,java]
----
ProcessInstance process = engine.getOperations().process("printenv")
        .arguments("TEST_VARIABLE").env("TEST_VARIABLE", "TEST").outputAsString().run();
----

.Example of running an external executable with an additional environment in Python
[source,python]
----
process = sponge.process("printenv").arguments("TEST_VARIABLE")
                .env("TEST_VARIABLE", "TEST").outputAsString().run()
----

For more examples see {sourcesUrl}/sponge-core/src/test/java/org/openksavi/sponge/core/util/process/ProcessInstanceTest.java[ProcessInstanceTest.java].

== Python (CPython) / Py4J
{sponge} may communicate with external programs written in the reference implementation of the Python programming language - https://en.wikipedia.org/wiki/CPython[CPython] using https://www.py4j.org[Py4J], and vice versa. A Python program and a {sponge} Java process communicate through network sockets.

Py4J by default uses the TCP port 25333 to communicate from Python to Java and TCP port 25334 to communicate from Java to Python.

There is no support for writing knowledge bases in CPython.

In the following examples Python 3 will be used.

The CPython environment must have Py4J installed, e.g.:

[source,bash]
----
pip3 install py4j
----

For more information on Py4J see https://www.py4j.org/advanced_topics.html.

[discrete]
=== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-py4j</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

=== Py4J plugins
{sponge} provides two plugins for integration with CPython.

WARNING: Local network sockets used by Py4j should be secured, for example using https://www.py4j.org/advanced_topics.html#tls[TLS]. Please be aware that all {sponge} operations are accessible in other processes that communicate with the {sponge} with Py4J enabled by a plugin. See {py4jSourcesUrl}/java_server_tls for an example of TLS security, based on Py4J examples. Note that in a production environment you should customize this simple configuration, possibly by providing your own configured instance of `GatewayServer` or `ClientServer` to the plugin.

.Py4J plugin common configuration parameters
[cols="2,1,4"]
|===
|Name |Type |Description

|`facadeInterface`
|`String`
|A Java interface that is a facade to the Py4J entry point object configured on the CPython side.

|`javaPort`
|`int`
|Java side server port.

|`pythonPort`
|`int`
|CPython side server port.

|`security`
|XML element/`SslConfiguration`
|The simple SSL security configuration.

|`security/keyStore`
|`String`
|Simple security keystore file location on the classpath.

|`security/keyStorePassword`
|`String`
|Simple security keystore password.

|`security/keyPassword`
|`String`
|Simple security key password.

|`security/algorithm`
|`String`
|Simple security algorithm. The default value is `SunX509`.

|`pythonScript`
|<<integration-external-subprocess,XML element/ProcessConfiguration>>
|The configuration of the CPython script that can be run as a subprocess of the {sponge} Java process when the plugin is starting up. Typically such script would init the Py4J connection on the CPython side. The plugin automatically adds to the environment variables for the subprocess: `PY4J_JAVA_PORT`, `PY4J_PYTHON_PORT` and optionally `PY4J_AUTH_TOKEN`.

|`pythonScriptBeforeStartup`
|`boolean`
|If `true`, the CPython script will be started before this plugin startup (the default value), otherwise it will be started after this plugin startup.

|`generateAuthToken`
|`boolean`
|If `true`, the plugin will generate the Py4J auth token (for both sides). The default value is `false`. This option is useful when combined with the `pythonScript`.

|`authToken`
|`String`
|The manual or generated Py4J auth token (for both sides).

|`randomPorts`
|`boolean`
|If `true`, the plugin will use random ports (for both sides). The default value is `false`. This option is useful when combined with the `pythonScript`.
|===

==== GatewayServerPy4JPlugin

`GatewayServerPy4JPlugin` provides integration with CPython using Py4J `GatewayServer`.

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/py4j/GatewayServerPy4JPlugin.html[`GatewayServerPy4JPlugin` Javadoc].

[discrete]
===== {sponge} side example

.GatewayServerPy4JPlugin XML configuration example
[source,xml,subs="verbatim,attributes"]
----
<sponge>
    <plugins>
        <plugin name="py4j" class="org.openksavi.sponge.py4j.GatewayServerPy4JPlugin" />
    </plugins>
</sponge>
----

[discrete]
===== CPython side example

.Sending {sponge} event in CPython
[source,python]
----
from py4j.java_gateway import JavaGateway

gateway = JavaGateway()

# The Sponge in other process accessed via Py4J
sponge = gateway.entry_point

print "Connected to {}".format(sponge.getInfo())
sponge.event("helloEvent").set("say", "Hello from Python's Py4J").send()
----

Note that a simplified bean property access is not supported here. So instead of `sponge.info` you have to invoke `sponge.getInfo()`.

==== ClientServerPy4JPlugin

`ClientServerPy4JPlugin` provides integration with CPython using Py4J `ClientServer`.

.ClientServerPy4JPlugin plugin specific configuration parameters
[cols="1,1,4"]
|===
|Name |Type |Description

|`autoStartJavaServer`
|`Boolean`
|Auto start of Py4J JavaServer.
|===

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/py4j/ClientServerPy4JPlugin.html[`ClientServerPy4JPlugin` Javadoc].

[discrete]
===== {sponge} side example

.ClientServerPy4JPlugin XML configuration example
[source,xml,subs="verbatim,attributes"]
----
<sponge>
    <plugins>
        <plugin name="py4j" class="org.openksavi.sponge.py4j.ClientServerPy4JPlugin">
            <configuration>
                <facadeInterface>org.openksavi.sponge.py4j.PythonService</facadeInterface>
            </configuration>
        </plugin>
    </plugins>
</sponge>
----

.Python facade interface
[source,java]
----
public interface PythonService {
    String toUpperCase(String text);
}
----

.ClientServerPy4JPlugin knowledge base example written in Jython
[source,python]
----
# Note that this code is interpreted by Jython in Sponge, not CPython
class PythonUpperCase(Action):
    def onCall(self, text):
        result = py4j.facade.toUpperCase(text)
        self.logger.debug("CPython result for {} is {}", text, result)
        return result
----

[discrete]
===== CPython side example

.Implementation of the facade interface in CPython
[source,python]
----
from py4j.clientserver import ClientServer

class PythonService(object):
    def toUpperCase(self, text):
        return text.upper()
    class Java:
        implements = ["org.openksavi.sponge.py4j.PythonService"]

pythonService = PythonService()
gateway = ClientServer(python_server_entry_point=pythonService)
----

=== Executing an external Python script
The plugin may run a CPython script as a subprocess.

.Example of an XML configuration for executing an external Python script
[source,xml]
----
    <plugins>
        <plugin name="py4j" class="org.openksavi.sponge.py4j.GatewayServerPy4JPlugin">
            <configuration>
                <pythonScript>
                    <executable>python3</executable>
                    <argument>${sponge.configDir}/cpython_script.py</argument>
                    <waitSeconds>60</waitSeconds>
                    <waitForOutputLineRegexp>The CPython service has started.</waitForOutputLineRegexp>
                    <outputRedirect>CONSUMER</outputRedirect>
                </pythonScript>
                <pythonScriptBeforeStartup>false</pythonScriptBeforeStartup>
            </configuration>
        </plugin>
    </plugins>
----

== ReactiveX
The ReactiveX plugin (`ReactiveXPlugin`) provides support for using http://reactivex.io[ReactiveX] in knowledge bases, e.g. for processing stream of {sponge} events using reactive programming. The plugin uses https://github.com/ReactiveX/RxJava[RxJava library]. The current version of the plugin is very simple and hasn't got any configuration parameters.

The default name of the ReactiveX plugin (which can be used in knowledge bases) is `rx`.

The main object provided by this plugin is an instance of a hot observable (`rx.observable`) that emits all non system {sponge} events. The plugin registers a Java-based correlator that listens to {sponge} events and sends them to the observable.

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/reactivex/ReactiveXPlugin.html[`ReactiveXPlugin` Javadoc].

The following example shows how to use reactive programming in a {sponge} knowledge base.

.Example Python knowledge base - Reactive programming
[source,python]
----
import time
from io.reactivex.schedulers import Schedulers

def onStartup():
    sponge.event("e1").set("payload", 1).send()
    sponge.event("e2").set("payload", 2).sendAfter(500)
    sponge.event("e3").set("payload", 3).sendAfter(1000)

    rx.observable.subscribe(lambda event: sponge.logger.info("{}", event.name))

    def observer(event):
        time.sleep(1)
        sponge.logger.info("After sleep: {}", event.name)
    rx.observable.observeOn(Schedulers.io()).subscribe(observer)
----

.Example XML configuration
[source,xml]
----
<sponge>
    <knowledgeBases>
        <knowledgeBase name="kb">
            <file>reactivex.py</file>
        </knowledgeBase>
    </knowledgeBases>
    <plugins>
        <plugin name="rx" class="org.openksavi.sponge.reactivex.ReactiveXPlugin" />
    </plugins>
</sponge>
----

[discrete]
=== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-reactivex</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

== MIDI
The MIDI plugin (`MidiPlugin`) allows processing https://en.wikipedia.org/wiki/MIDI[MIDI] messages by the {sponge} and provides communication with MIDI devices. It wraps MIDI messages in {sponge} events. The plugin supports `ShortMessage`, `MetaMessage` and `SysexMessage` MIDI messages wrapping them respectively in `MidiShortMessageEvent`, `MidiMetaMessageEvent` and `MidiSysexMessageEvent` {sponge} events. Although the MIDI support in the {sponge} provides a set of methods that use the `javax.sound.midi` API, the goal of this plugin is not to be a complete interface to the MIDI system but a bridge between MIDI messages and {sponge} events.

The default name of the MIDI plugin (which can be used in knowledge bases) is `midi`.

.MIDI plugin configuration parameters
[cols="1,1,4"]
|===
|Name |Type |Description

|`sequencerConnectedToSynthesizer`
|`Boolean`
|If `true` then the default MIDI sequencer will be connected to the default synthesizer (e.g. to generate sound while playing MIDI files). The default value is `false`.

|`loadAllInstruments`
|`Boolean`
|If `true` then all instruments in the default soundbank will be loaded at startup. The default value is `true`.

|`midiShortMessageEventName`
|`String`
|A name of a MIDI ShortMessage {sponge} event sent by this plugin to the engine. The default value is `"midiShort"`.

|`midiMetaMessageEventName`
|`String`
|A name of a MIDI MetaMessage {sponge} event sent by this plugin to the engine. The default value is `"midiMeta"`.

|`midiSysexMessageEventName`
|`String`
|A name of a MIDI SysexMessage {sponge} event sent by this plugin to the engine. The default value is `"midiSysex"`.
|===

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/midi/MidiPlugin.html[`MidiPlugin` Javadoc].

.Example Python knowledge base that shows how to process MIDI messages created by an external MIDI input device
[source,python]
----
from javax.sound.midi import ShortMessage
from org.openksavi.sponge.midi import MidiUtils

class SameSound(Trigger):
    def onConfigure(self):
        self.withEvent("midiShort") # <1>
    def onRun(self, event):
        midi.sound(event.message) # <2>

class Log(Trigger):
    def onConfigure(self):
        self.withEvent("midiShort")
    def onRun(self, event):
        self.logger.info("{}Input message: {}", "[" + MidiUtils.getKeyNote(event.data1) + "] " if event.command == ShortMessage.NOTE_ON else "",
                         event.messageString) # <3>

def onStartup():
    sponge.logger.info("This example program enables a user to play an input MIDI device (e.g. a MIDI keyboard) using the Sponge MIDI plugin.")
    midi.connectDefaultInputDevice() # <4>
    sponge.logger.info("Input MIDI device: {}", midi.inputDevice.deviceInfo.name)
    sponge.logger.info("Instruments: {}", ",".join(list(map(lambda i: i.name + " (" + str(i.patch.bank) + "/" + str(i.patch.program) + ")", midi.instruments))))
    midi.setInstrument(0, "Electric Piano 1") # <5>
----
<1> The trigger `SameSound` listens to all MIDI short messages.
<2> The trigger `SameSound` sends all MIDI short messages received from the input MIDI device to the MIDI synthesizer to generate sounds. It is achieved through the use of the `sound` method in the `midi` plugin.
<3> The trigger `Log` only logs a MIDI message info and a note for _note on_ MIDI messages.
<4> Connects a default input MIDI device in the system (e.g. a MIDI keyboard) to the MIDI plugin in order to receive all MIDI messages generated by this device and send them to the {sponge} engine as {sponge} events.
<5> Sets the instrument (by name) in the MIDI synthesizer for the MIDI channel `0`. Note that this example assumes that the input MIDI device will generate MIDI messages for the same channel.

NOTE: An event flow in the {sponge} engine introduces an additional performance overhead that in some situations may be not acceptable when dealing with real-time physical MIDI instruments.

[discrete]
=== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-midi</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

== Raspberry Pi - Pi4J
The Pi4J plugin (`Pi4JPlugin`) allows using the http://pi4j.com[Pi4J] library in {sponge} knowledge bases. The Pi4J library provides a friendly object-oriented I/O API and implementation libraries to access the full I/O capabilities of the Raspberry Pi platform. The current version of the plugin is very simple and hasn't got any configuration parameters.

The default name of the Pi4J plugin (which can be used in knowledge bases) is `pi4j`.

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/rpi/pi4j/Pi4JPlugin.html[`Pi4JPlugin` Javadoc].

NOTE: The Pi4J documentation states that _You must now have WiringPi installed on your target Raspberry Pi system separately from Pi4J. WiringPi is now included be default in the latest Raspbian builds._

The following example shows how to turn on/off a Grove LED connected to the Raspberry Pi GPIO. The hardware setup for this example includes Raspberry Pi 3, a ribbon cable, a ribbon cable socket, a breadboard, a 4-pin male jumper to Grove 4 pin conversion cable and a Grove LED. Before setting up the hardware make sure that your Raspberry Pi is not powered! The Grove LED should be connected to GPIO via a 4-pin connector: the black wire goes on PIN#14 (Ground), the red wire goes on PIN#02 (DC Power 5V), the yellow wire goes on PIN#12 (GPIO18/GPIO_GEN1), the white wire goes on PIN#06 (Ground).

.Example Python knowledge base - Blinking LED
[source,python]
----
from com.pi4j.io.gpio import RaspiPin, PinState

state = False

class LedBlink(Trigger):
    def onConfigure(self):
        self.withEvent("blink")
    def onRun(self, event):
        global led, state
        state = not state
        led.setState(state)

def onStartup():
    global led
    led = pi.gpio.provisionDigitalOutputPin(RaspiPin.GPIO_01, "led", PinState.LOW)
    sponge.event("blink").sendAfter(0, 1000)

def onShutdown():
    off()

on = lambda: led.setState(True)
off = lambda: led.setState(False)
----

.Example XML configuration
[source,xml]
----
<sponge>
    <properties>
        <!-- Due to the problem https://github.com/Pi4J/pi4j/issues/319, the dynamic linking option is turned on, where Pi4J is dynamically linked
            to WiringPi rather than the default static linking. -->
        <property name="pi4j.linking" system="true">dynamic</property>
    </properties>
    <knowledgeBases>
        <knowledgeBase name="kb">
            <file>pi4j_led_blink.py</file>
        </knowledgeBase>
    </knowledgeBases>
    <plugins>
        <plugin name="pi" class="org.openksavi.sponge.rpi.pi4j.Pi4JPlugin" />
    </plugins>
</sponge>
----

[discrete]
=== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-rpi-pi4j</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

== Raspberry Pi - GrovePi
The GrovePi plugin (`GrovePiPlugin`) allows accessing the https://github.com/DexterInd/GrovePi[GrovePi] hardware in {sponge} knowledge bases. GrovePi is an electronics board for Raspberry Pi that may have a variety of sensors and actuators connected to. The plugin uses https://github.com/DexterInd/GrovePi/tree/master/Software/Java8[Java 8 GrovePi library]. The current version of the plugin is very simple and hasn't got any configuration parameters.

The default name of the GrovePi plugin (which can be used in knowledge bases) is `grovepi`.

IMPORTANT: If using this plugin in an embedded {sponge}, you have to manually install the https://github.com/DexterInd/GrovePi/tree/master/Software/Java8[Java 8 GrovePi library] in you local Maven repository because it isn't available in the Central Maven Repository.

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/rpi/grovepi/GrovePiPlugin.html[`GrovePiPlugin` Javadoc].

The following example shows how to turn on/off a LED connected to the GrovePi board that in turn is connected to the Raspberry Pi.

.Example Python knowledge base - Blinking LED
[source,python]
----
# GrovePi board: Connect LED to D4

state = False

class LedBlink(Trigger):
    def onConfigure(self):
        self.withEvent("blink")
    def onRun(self, event):
        global led, state
        state = not state
        led.set(state)

def onStartup():
    global led
    led = grovepi.device.getDigitalOut(4)
    sponge.event("blink").sendAfter(0, 1000)
----

.Example XML configuration
[source,xml]
----
<sponge>
    <knowledgeBases>
        <knowledgeBase name="kb">
            <file>led_blink.py</file>
        </knowledgeBase>
    </knowledgeBases>
    <plugins>
        <plugin name="grovepi" class="org.openksavi.sponge.rpi.grovepi.GrovePiPlugin" />
    </plugins>
</sponge>
----

[discrete]
=== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-rpi-grovepi</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

include::user-guide-integration-tensorflow.adoc[leveloffset=+1]

== GSM modem
{sponge} provides access to a GSM modem device. The `GammuGsmModemPlugin` uses https://wammu.eu/gammu/[Gammu]. The requirement is that Gammu utility has to be installed. The current implementation of the `GammuGsmModemPlugin` is limited. It only sends SMSes. However you may invoke `gammu` in a knowledge base using the {sponge} `ProcessInstance` API.

The default name of the plugin (which can be used in knowledge bases) is `gsm`.

.Example of sending SMS using the `GammuGsmModemPlugin`
[source,python]
----
class SendSms(Action):
    def onConfigure(self):
        self.withLabel("Send an SMS").withDescription("Sends a new SMS.")
        self.withArgs([
            StringType("recipient").withFormat("phone").withLabel("Recipient").withDescription("The SMS recipient."),
            StringType("message").withMaxLength(160).withFeatures({"maxLines":5}).withLabel("Message").withDescription("The SMS message.")
        ]).withNoResult()
    def onCall(self, recipient, message):
        gsm.sendSms(recipient, message)
----

.Example XML configuration
[source,xml]
----
<plugin name="gsm" class="org.openksavi.sponge.gsmmodem.GammuGsmModemPlugin" />
----

.Example of sending SMS using the `ProcessInstance` API
[source,python]
----
def sendSms(recipient, message):
    process = sponge.process("gammu").arguments("sendsms", "TEXT", recipient,
            None if gsm.canEncodeGsm(message) else "-unicode")
            .inputAsString(message).outputAsString().run()
    if process.exitCode != 0:
        raise Exception("Exit code {}: {}".format(process.exitCode, process.outputString))
----

[discrete]
=== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-gsm-modem</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

