= Rules
Sometimes there is a need to perform certain actions when a sequence of events has happened, additionally fulfilling some conditions. To handle such event relationships (both temporal and logical), {sponge} provides rules. It is important for the behavior of the rules that events that happened first must be sent first into the engine.

The alias for the base class for script-based rules is `Rule`. The base class for Java-based rules is `JRule`.

A rule group is a set of rule instances, each created automatically for every event that could be accepted as the first event of this rule.

== Properties and methods
In addition to the inherited <<processor-methods,processor properties and methods>>, rules provide the following ones.

.Rule properties and methods
[cols="2,5"]
|===
|Property / Method |Description

|*`onConfigure()`*
|The callback method that is invoked only once, when a rule is being enabled. In this method it should be established for what type of events the rule listens. Optionally event conditions for incoming events or rule duration could be set. This method is mandatory.

|`onInit()`
|The initialization callback method that is invoked while creating every new rule instance but after `onConfigure`.

|*`withEvents(List<String> eventStringSpecs)` or `withEvent(String eventStringSpec)`*
|Sets String-based specifications of events whose sequence causes the rule to fire. The complete event specifications can be read using `self.meta.eventSpecs`. Setting an event or events is mandatory. It should be set in the `onConfigure` callback method. You may use only one of these methods in a processor.

|`withDuration(Duration duration)`
|Sets a duration that may be used to set the time how long a rule lasts (represented as a {javaSeJavaDocUrl}/java/time/Duration.html[`Duration`]). The instance of a rule will be active only for a given period of time since the arrival of the first event. Until that time the instance of the rule will fire for each suitable event sequence that happens.

|`withSynchronous(Boolean synchronous)`
|Sets a _synchronous flag_ for a rule. If a rule is synchronous it means that an event will be processed sequentially (in one thread) for all instances of this rule. If a rule is asynchronous then an event will be processed by the instances of this rule concurrently (in many threads). If the _synchronous flag_ is not set then the default value as specified by `eventSetProcessorDefaultSynchronous` configuration parameter will be used. In most cases there should be no need to change this flag.

|`withConditions(String eventAlias, List<_event condition_> conditions)`
|Adds conditions for an event specified by an alias (or event name if aliases are not used). A condition is a method of this class or a closure/lambda that is invoked to verify that a new incoming event corresponds to this rule. The name of the condition method is irrelevant.

|`withCondition(String eventAlias, _event condition_ condition)`
|Adds a single condition for an event.

|`withAllConditions(List<_event condition_> conditions)`
|Adds conditions for all events. This method must be invoked *after* the event specifications.

|`withAllCondition(_event condition_ condition)`
|Adds a single condition for all events. This method must be invoked *after* the event specifications.

|`withEventSpecs(List<RuleEventSpec> eventSpecs)` or `withEventSpec(RuleEventSpec eventSpec)`
|Sets complete specifications of events whose sequence causes the rule to fire. The preferred way is to use String-based specifications of events.

|`withOrdered(boolean ordered)`
|Sets a flag indicating that the rule should listen to ordered (ordered rule) or unordered (unordered rule) sequences of events. *Defaults to `true`, i.e. the rule would listen to ordered sequences of events.*

|*`onRun(event)`*
|The callback method invoked when a sequence of events specified by this rule has happened and all the conditions have been fulfilled. The argument `event` is the reference to the final event that caused this rule to fire. There could be many sequences of events fitting the rule definition. In order to access the events which fulfilled the conditions and caused the rule fire, the `getEvent(eventAlias)` method should be used. The `onRun` method is mandatory.

|`Event getEvent(String eventAlias)`
|Returns the instance of the event that already happened and that has a specified alias. This method may be used inside `onRun` method. If an event hasn't happened yet, this method throws an exception. This method may return `null` only when an event that supposed not to happen didn't occur as specified.

|`firstEvent`
|This property is a reference to the first event that has been accepted by this rule. It is a shortcut for the `Event getFirstEvent()` method. It could be used for example in event condition methods (including the one for the first event itself).

|`eventSequence`
|Returns a sequence of events that happened, as a list of event instances. The sequence may contain `null` values when an event that supposed not to happen didn't occur as specified. This method may be used inside `onRun` method. 
|===

Every rule should implement the abstract `onConfigure` and `onRun` methods.

IMPORTANT: Because of rules are not singletons the `onConfigure()` method is invoked *only once*, while enabling the rule. So it should contain only basic configuration as stated before. The `onInit()` method *must not* contain such configuration because it is invoked every time the new instance of the rule is created.

NOTE: A duration is relative to an internal clock of the engine, that is related to the time of events. When a duration timeout occurs, the engine sends a control event (`DurationControlEvent`) to the Input Event Queue so that the control event, before finishing the rule, goes the same route as all events. This is to ensure that no events will be skipped by a rule if the system is highly loaded. Note that this may cause the rule to last longer in terms of an external clock.

.Rule builder specific properties and methods
[cols="1,5"]
|===
|Property / Method |Description

|`*withOnRun(RuleOnRunCallback onRunCallback)*`
|Configures the `onRun()` callback function that takes arguments: the rule instance and an event, e.g. `withOnRun(lambda rule, event: rule.logger.info("OK"))`.
|===

NOTE: Rule builders don't support multi condition configuration methods, i.e. `withConditions` and `withAllConditions`. You have to invoke single condition versions of these methods.

== Event specification
Event specification for the rule consists of:

Event name:: A name (or name pattern) of the event (mandatory).
Event alias:: An optional alias for the event. The alias is a unique (in the scope of the rule) name assigned to the event. Aliases are mandatory if there is more than one event of the same type (i.e. having the same name). When each of the events is of different type, there is no need to specify an alias. In such case aliases will be defined automatically and equal to the name of the corresponding event.
Event mode:: Specifies which sequences of events suitable to this rule should be used for running the rule (i.e. invoking the `onRun` callback method). Event modes are defined in the `EventMode` Java enumeration.
+
.Rule event modes
[cols="1,4"]
|===
|Event mode |Description

|`first`
|The first suitable event. This is the default event mode when none is specified for an event.

|`last`
|The last suitable event for the duration of the rule.

|`all`
|All suitable events for the duration of the rule.

|`none`
|An event that cannot happen in the sequence.
|===
+

Event specification should be formatted as text `"eventName [eventAlias [:eventMode"]]` or `"eventNamePattern [eventAlias [:eventMode"]]`. White characters between all elements are allowed. For example the specifications `"event1 e1 :first"`, `"event1"`, `"event1 e1"` define the suitable first event named `"event1"`. The specification `"[Ee]vent.* e"` define all events which name starts with `"Event"` or `"event"`.

== Ordered rules

For ordered rules:

* The first event in the sequence, i.e. the event that would initiate the rule, must always have the mode `first`.
* If the mode of the last (final) specified event is `last` or `none`, a duration must be set. Otherwise the rule would never fire.

The following examples of complete event specifications assume that the ordered rule has a duration that spans over all incoming events listed in the second column. The integer value in the brackets is the `id` of the event. An element `null` means that the event hasn't happened. Incoming events: `e1[1]`, `e2[2]`, `e2[3]`, `e3[4]`, `e2[5]`, `e3[6]`, `e3[7]`.

.Examples of ordered event specifications
[cols="1,3"]
|===
|Events specification |Event sequences

|`["e1", "e2 :all", "e3 :all"]`
|`[e1[1], e2[2], e3[4]], [e1[1], e2[3], e3[4]], [e1[1], e2[2], e3[6]], [e1[1], e2[3], e3[6]], [e1[1], e2[5], e3[6]], [e1[1], e2[2], e3[7]], [e1[1], e2[3], e3[7]], [e1[1], e2[5], e3[7]]`

|`["e1", "e2 :all", "e3"]`
|`[e1[1], e2[2], e3[4]], [e1[1], e2[3], e3[4]]`

|`["e1", "e2 :all", "e3 :last"]`
|`[e1[1], e2[2], e3[7]], [e1[1], e2[3], e3[7]], [e1[1], e2[5], e3[7]]`

|`["e1", "e2 :all", "e4 :none"]`
|`[e1[1], e2[2], null], [e1[1], e2[3], null], [e1[1], e2[5], null]`

|`["e1", "e2", "e3 :all"]`
|`[e1[1], e2[2], e3[4], [e1[1], e2[2], e3[6]], [e1[1], e2[2], e3[7]]`

|`["e1", "e2", "e3"]`
|`[e1[1], e2[2], e3[4]]`

|`["e1", "e2", "e3 :last"]`
|`[e1[1], e2[2], e3[7]]`

|`["e1", "e2", "e4 :none"]`
|`[e1[1], e2[2], null]`

|`["e1", "e2 :last", "e3 :all"]`
|`[e1[1], e2[3], e3[4]], [e1[1], e2[5], e3[6]], [e1[1], e2[5], e3[7]]`

|`["e1", "e2 :last", "e3"]`
|`[e1[1], e2[3], e3[4]]`

|`["e1", "e2 :last", "e3 :last"]`
|`[e1[1], e2[5], e3[7]]`

|`["e1", "e2 :last", "e4 :none"]`
|`[e1[1], e2[5], null]`

|`["e1", "e4 :none", "e3 :all"]`
|`[e1[1], null, e3[4]], [e1[1], null, e3[6]], [e1[1], null, e3[7]]`

|`["e1", "e4 :none", "e3"]`
|`[e1[1], null, e3[4]]`

|`["e1", "e4 :none", "e3 :last"]`
|`[e1[1], null, e3[7]]`

|`["e1", "e2", "e3 :none"]`
|_This rule hasn't been fired because the event_ `e3` _wasn't supposed to happen._
|===

== Unordered rules

Behavior:

* The matching of unordered events is done starting from the left in the list of events the unordered rule listens to.
* Every event that is relevant to the unordered rule causes a new instance of the rule to be created. This implicates that the event mode for an event that actually happens as the first is used by the engine only as a suggestion. So the actual order of events that happen has a significant impact on the behavior of unordered rules.
* If at least one specified event has `none` mode, you probably should set a duration for such a rule to avoid superfluous instances of the rule.

IMPORTANT: Unordered rules should be treated as an experimental feature.

== Event conditions
A rule may define conditions for events that have to be met to consider an incoming event as corresponding to the rule:

* of the form of a any class method that takes one argument (`Event`) and returns `boolean`, e.g.:
+
[source,java]
----
boolean conditionA(Event event);
boolean check1(Event event);
----
* as a closure or a lambda (depending on the language) that takes two arguments (`Rule`, `Event`) and returns `boolean`, e.g.:
+
[source,python]
----
lambda rule, event: Duration.between(rule.getEvent("filesystemFailure").time, event.time).seconds > 2
----
* as an instance of an implementation of the interface `EventCondition` (takes two arguments (`Rule`, `Event`) and returns `boolean`), e.g. as a Java lambda expression:
+
[source,java]
----
(rule, event) -> {
    return true;
};
----

An event condition in Java is represented by the interface `EventCondition`.

IMPORTANT: A condition in the form of a closure or a lambda specifies two arguments: a rule instance (determined at the runtime) and an event instance. Take care not to mix up the `rule` argument with `this` (in Java) or `self` (in Python) as they are references to different objects.

The condition methods tell if an incoming event (corresponding to the sequence of events specified by the rule) should be considered suitable.

[discrete]
== Example in a script language
The code presented below defines a rule named `SameSourceAllRule` listening to an ordered sequence of events (`"filesystemFailure"`, `"diskFailure"`).
The two events have to have `severity` greater than `5` and the same `source`. Moreover the second event has to happen not later than after `4` seconds since the first one. The method `onRun()` will be invoked for every sequence of events that match this definition.

.Rule example
[source,python]
----
class SameSourceAllRule(Rule): # <1>
    def onConfigure(self): # <2>
        # Events specified with aliases (e1 and e2)
        self.withEvents(["filesystemFailure e1", "diskFailure e2 :all"]) # <3>
        self.withAllCondition(self.severityCondition) # <4>
        self.withCondition("e2", self.diskFailureSourceCondition) # <5>
        self.withDuration(Duration.ofSeconds(8)) # <6>
    def onRun(self, event): # <7>
        self.logger.info("Monitoring log [{}]: Critical failure in {}! Events: {}",
            event.time, event.get("source"), self.eventSequence) # <8>
    def severityCondition(self, event): # <9>
        return int(event.get("severity")) > 5 # <10>
    def diskFailureSourceCondition(self, event): # <11>
        event1 = self.getEvent("e1") # <12>
        return event.get("source") == event1.get("source") and \
            Duration.between(event1.time, event.time).seconds <= 4 # <13>
----
<1> The definition of the rule `SameSourceAllRule`. The rule is represented by a class of the same name.
<2> The rule configuration callback method.
<3> Defines that the rule is supposed to wait for sequences of events `"filesystemFailure"` (alias `"e1"`) and `"diskFailure"` (alias `"e2"`) and take into consideration the first occurrence of `"e1"` event and all occurrences of `"e2"` event.
<4> Sets the condition checking an event severity for all events.
<5> Sets conditions checking `"e2"` event source.
<6> Setting the duration of the rule. The duration must be set for this rule because the final event has `all` mode. The rule lasts for `8` seconds. So, for `8` seconds since the occurrence of the first matching `e1` a tree of event instances will be constantly built with the root containing the instance of initial `e1` event. Each matching `e2` event will cause the rule to fire immediately for the current event sequence. After reaching the duration time this rule instance will be discarded.
<7> The `onRun` method will be called when the proper sequence of events happens and all the conditions have been fulfilled. The `event` argument specifies the last event in that sequence.
<8> Logs message and the sequence of events.
<9> An event condition method `severityCondition`.
<10> Accept only events that have `severity` greater than `5`.
<11> An event condition method `diskFailureSourceCondition`.
<12> Assigns the first event (`e1`) to the local variable `event1`.
<13> Accept `e2` events that have the same `source` as the first event `e1` and that happened not later than after `4` seconds since the corresponding `e1` event.

The rule will be enabled automatically. Then, in case of occurrence of `e1` event that has `severity` greater than `5`, a new instance of a rule `SameSourceAllRule` will be created.

A condition could be expressed as a lambda function, for example:
[source,python]
----
self.withCondition("e1", lambda rule, event: int(event.get("severity")) > 5)
----

[discrete]
== Example in Java
The code presented below defines a rule analogous to the one shown above but defined as a Java class.

.Java rule example
[source,java]
----
public class SameSourceJavaRule extends JRule { // <1>

    private static final Logger logger = LoggerFactory.getLogger(SameSourceJavaRule.class);

    @Override
    public void onConfigure() {
        withEventSpecs(new RuleEventSpec("filesystemFailure", "e1"), new RuleEventSpec("diskFailure", "e2", EventMode.ALL)); // <2>
        withAllConditions("severityCondition"); // <3>
        withConditions("e2", (rule, event) -> { // <4>
            Event event1 = rule.getEvent("e1");
            return event.get("source").equals(event1.get("source")) &&
                    Duration.between(event1.getTime(), event.getTime()).getSeconds() <= 4;
        });
        withDuration(Duration.ofSeconds(8)));
    }

    @Override
    public void onRun(Event event) {
        logger.info("Monitoring log [{}]: Critical failure in {}! Events: {}", event.getTime(), event.get("source"),
                getEventAliasMap());
    }

    public boolean severityCondition(Event event) { // <5>
        return event.get("severity", Number.class).intValue() > 5;
    }
}
----
<1> The definition of the rule `SameSourceAllRule`. The rule is represented by a Java class of the same name.
<2> The `RuleEventSpec` class is used here to create event specifications instead of a formatted String. The same setting could be achieved by `withEvents("filesystemFailure e1", "diskFailure e2 :all")`.
<3> Sets the condition checking an event severity for all events.
<4> Sets conditions checking `"e2"` event source (as a Java lambda expression).
<5> An event condition method `severityCondition`.

.Java rule manual registration in the Python knowledge base
[source,python]
----
sponge.enableJava(SameSourceJavaRule)
----

[discrete]
== Example of a rule builder
The code presented below defines and enables a rule named `SameSourceAllRule`. Note that Python doesn't support multi-expression lambda functions.

.Rule builder example
[source,python]
----
def onLoad():
    def sameSourceAllRuleE2Condition(rule, event):
        event1 = rule.getEvent("e1")
        return event.get("source") == event1.get("source") and Duration.between(event1.time, event.time).seconds <= 4

    def sameSourceAllRuleOnRun(rule, event):
        rule.logger.info("Monitoring log [{}]: Critical failure in {}! Events: {}", event.time, event.get("source"),
                                                                                          rule.eventSequence)
        sponge.getVariable("hardwareFailureScriptCount").incrementAndGet()

    sponge.enable(RuleBuilder("SameSourceAllRule").withEvents(["filesystemFailure e1", "diskFailure e2 :all"])
                .withCondition("e1", lambda rule, event: int(event.get("severity")) > 5)
                .withCondition("e2", sameSourceAllRuleE2Condition)
                .withDuration(Duration.ofSeconds(8)).withOnRun(sameSourceAllRuleOnRun))
----
