= Standalone command-line application
For a brief introduction to the {sponge} standalone command-line application see Quickstart.

If you need additional libraries (e.g. Camel components) you should place JAR files into the `lib` directory. You should use only compatible versions of these libraries.

Standalone command-line application doesn't support history of entered commands/expressions (i.e. upwards arrow doesn't work).

== Command-line options

[cols="1,4"]
|===
|Option |Description

|`-c <arg>`
|Use given Sponge XML configuration file. Only one configuration file may be provided.

|`-k [name=]files`
|Use given knowledge base by setting its name (optional) and files (comma-separated). When no name is provided, a default name 'kb' will be used. This option may be used more than once to provide many knowledge bases. Each of them could use many files.

|`-s <file>`
|Use given Spring configuration file. This option may be used more than once to provide many Spring configuration files.

|`-m`
|Create an Apache Camel context.

|`-i [name]`
|Run in an interactive mode by connecting to a knowledge base interpreter. You may provide the name of one of the loaded knowledge bases, otherwise the first loaded knowledge base will be chosen.

|`-e`
|Applicable only in an interactive mode. Print all exceptions (e.g. also thrown in event processors running in other threads). Helpful for development purposes.

|`-h`
|Print help message and exit.

|`-v`
|Print the version information and exit.
|===

== Default parameters
Standalone command-line application sets its own default values for the following engine configuration parameters. You may change them in an XML configuration file.

[width=80%]
|===
|Parameter |Value

|`mainProcessingUnitThreadCount`
|`10`

|`asyncEventSetProcessorExecutorThreadCount`
|Same as `mainProcessingUnitThreadCount`

|`eventQueueCapacity`
|`100000`
|===


.Examples
[source,bash,subs="verbatim,attributes"]
----
# Change directory to Sponge bin/.

# Run with the specified {sponge} XML configuration file.
./sponge -c ../examples/script/py/triggers_hello_world.xml

# Run with the knowledge base named 'helloWorldKb' using the specified knowledge base file.
./sponge -k helloWorldKb=../examples/script/py/triggers_hello_world.py

# Run with the knowledge base named 'kb' using the specified knowledge base file.
./sponge -k ../examples/script/py/triggers_hello_world.py

# Run with two knowledge bases.
./sponge -k filtersKb=../examples/script/py/filters.py -k heartbeatKb=../examples/script/js/rules_heartbeat.js

# Run in an interactive mode.
./sponge -k filtersKb=../examples/script/py/filters.py -i

# Run in an interactive mode and setup printing all exceptions to the console.
./sponge -k filtersKb=../examples/script/py/filters.py -i -e

# Run one knowledge base that use two files. Take caution not to use the same names for functions or classes in the files belonging to the same knowledge base.
./sponge -k ../examples/standalone/multiple_kb_files/event_processors.py,../examples/standalone/multiple_kb_files/example2.py
----

== Environment variables
Optionally you may set the environment variable `SPONGE_HOME`.

.Linux/MacOS/Unix
[source,bash,subs="verbatim,attributes"]
----
cd {standaloneDir}
export SPONGE_HOME=`pwd`
----

.Windows
[source,bash,subs="verbatim,attributes"]
----
cd {standaloneDir}
set SPONGE_HOME=%cd%
----

== Standalone plugin configuration parameters

.Standalone plugin configuration parameters
[cols="1,1,4"]
|===
|Name |Type |Description

|`spring`
|XML element
|Spring configuration. A Spring context is created only when there is a `spring` configuration element present.

|`engineBeanName`
|`String`
|The optional `engineBeanName` attribute of the `spring` element defines a Spring bean name that will reference the engine instance in the Spring context. The default value is `spongeEngine`.

|`camel`
|`Boolean`
|The optional `camel` attribute of the `spring` element may be used to create a Camel context.

|`spring/file`
|`String`
|Spring configuration files. The Spring context implementation used here is `GenericGroovyApplicationContext`, that allows to load XML and Groovy configuration files.
|===

== Spring
You may provide Spring configuration files using a command-line option or defining `StandalonePlugin` plugin in {sponge} XML configuration file. This plugin allows to specify Spring configuration files that will be loaded. The name of this plugin must be `"standalonePlugin"`.

.Example of Spring configuration in StandalonePlugin
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="http://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://sponge.openksavi.org http://sponge.openksavi.org/schema/config.xsd">

    <plugins>
        <plugin name="standalonePlugin" class="org.openksavi.sponge.standalone.StandalonePlugin">
            <configuration>
                <spring engineBeanName="someEngine">
                    <file>spring-context-example-file-1.xml</file>
                    <file>spring-context-example-file-2.xml</file>
                    <file>SpringContextExample3.groovy</file>
                </spring>
            <configuration>
        </plugin>
    </plugins>
</sponge>
----

This `standlonePlugin` sets up the Spring configuration XML file and Spring bean name that will reference the engine instance.

== Camel
If you want to use Camel, you could setup a predefined Camel context configuration, so that a Camel context will be created automatically.

Available options are:

* Setting `<spring camel="true">` will create a Camel context using a predefined Spring Java configuration.
* Using `<spring>` without setting `camel` attribute will not create any Camel context automatically. In that case you may setup a Camel context in a custom way (for example using Spring).

You may use only one Camel context in the {sponge} standalone command-line application.

You could use Camel routes to send events to {sponge} from an external systems, for example by configuring http://camel.apache.org/rest-dsl.html[Camel Rest DSL].

=== Spring XML configuration

.Example of Spring configuration in StandalonePlugin
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="http://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://sponge.openksavi.org http://sponge.openksavi.org/schema/config.xsd">

    <plugins>
        <plugin name="standalonePlugin" class="org.openksavi.sponge.standalone.StandalonePlugin">
            <configuration>
                <spring camel="true">
                    <file>examples/standalone/camel_route_xml/spring-camel-xml-config-example.xml</file>
                </spring>
            </configuration>
        </plugin>
    </plugins>
</sponge>
----

.Camel configuration in Spring XML (spring-camel-xml-config-example.xml)
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:context="http://www.springframework.org/schema/context" xmlns:lang="http://www.springframework.org/schema/lang"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
                           http://www.springframework.org/schema/beans/spring-beans.xsd
                           http://camel.apache.org/schema/spring
                           http://camel.apache.org/schema/spring/camel-spring.xsd">

    <camelContext xmlns="http://camel.apache.org/schema/spring">
        <route id="spongeConsumerXmlSpringRoute">
            <from uri="sponge:spongeEngine" />
            <log message="XML/Spring route - Received message: ${body}" />
        </route>
    </camelContext>
</beans>
----

=== Spring Groovy configuration

.Spring container plugin in {sponge} configuration file example
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="http://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://sponge.openksavi.org http://sponge.openksavi.org/schema/config.xsd">

    <plugins>
        <plugin name="standalonePlugin" class="org.openksavi.sponge.standalone.StandalonePlugin">
            <configuration>
                <spring camel="true">
                    <file>examples/standalone/camel_route_groovy/SpringCamelGroovyConfigExample.groovy</file>
                </spring>
            </configuration>
        </plugin>
    </plugins>
</sponge>
----

.Camel configuration in Spring Groovy (SpringCamelGroovyConfigExample.groovy)
[source,groovy]
----
import org.apache.camel.builder.RouteBuilder;

class GroovyRoute extends RouteBuilder {
    void configure() {
        from("sponge:spongeEngine").routeId("spongeConsumerCamelGroovySpring")
                .log("Groovy/Spring route - Received message: \${body}");
    }
}

beans {
    route(GroovyRoute)
}
----

=== Management of Camel routes in an interactive mode

.Console - print camel status and routes
[source,bash]
----
> print(camel.context.status)
> print(camel.context.routes)
----

.Console - stop and remove a Camel route
[source,bash]
----
> camel.context.stopRoute("rss")
> print(camel.context.removeRoute("rss"))
> print(camel.context.routes)
----

== Logging and exception reporting

=== Non interactive mode
If you experience too many logs in the console while running a non-interactive standalone command-line application, you may want to change a logging configuration in `config/logback.xml`. For example to change a console threshold filter level from `INFO` to `ERROR`:

.Example logging configuration
[source,xml]
----
<appender name="console" class="ch.qos.logback.core.ConsoleAppender">
    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
        <level>ERROR</level>
    </filter>
----

=== Interactive mode
In an interactive mode a predefined console logger appender (configured in `config/logback.xml`) is turned off programmatically.

Exceptions thrown from other threads of the {sponge} engine are not printed into the console. You may change that behavior by specifying `-e` command-line option.

== REST API
You may enable the {sponge} REST API in the standalone command line application but such configuration will provide no user management and a very limited security. Thus it may be used only in a secure network or for test purposes.

Manual start of the REST API (`autoStart` must be turned off) is required because the REST API server must start after the Camel context has started.

For more information see examples in the source code.

== Running examples

.News example
[source,bash,subs="verbatim,attributes"]
----
# Change directory to Sponge bin/.

# Run with the specified {sponge} XML configuration file.
./sponge -c ../examples/standalone/news/config/config.xml
----

.Camel RSS News example
[source,bash,subs="verbatim,attributes"]
----
# Change directory to Sponge bin/.

# Run with the specified {sponge} XML configuration file.
./sponge -c ../examples/standalone/camel_rss_news/config/config.xml
----

== Directory structure

.Directory structure
[cols="1,5"]
|===
|Directory |Description

|`bin`
|Shell scripts.

|`config`
|Configuration files.

|`docs`
|Documentation.

|`examples`
|Example configurations and knowledge base files.

|`lib`
|Libraries used by {sponge}.

|`logs`
|Log files.
|===

== Camel components and data formats available out of the box
Besides Camel core components and data formats, {sponge} standalone command-line application provides also a selected set of other Camel components and data formats ready to use.

.Camel components out of the box
[width="75%"]
|===
|Component |Description

|http://camel.apache.org/amqp.html[camel-amqp] |AMQP
|http://camel.apache.org/bean-validator.html[camel-bean-validator] |Validation
|http://camel.apache.org/dns.html[camel-dns] |DNS
|http://camel.apache.org/docker.html[camel-docker] |Docker
|http://camel.apache.org/dropbox.html[camel-dropbox] |Dropbox
|http://camel.apache.org/ejb.html[camel-ejb] |EJB
|http://camel.apache.org/eventadmin.html[camel-eventadmin] |OSGi EventAdmin events
|http://camel.apache.org/exec.html[camel-exec] |Executing system commands
|http://camel.apache.org/facebook.html[camel-facebook] |Facebook
|http://camel.apache.org/ftp2.html[camel-ftp] |FTP
|http://camel.apache.org/geocoder.html[camel-geocoder] |Geocoder
|http://camel.apache.org/grape.html[camel-grape] |Grape
|http://camel.apache.org/http4.html[camel-http4] |HTTP
|http://camel.apache.org/mail.html[camel-mail] |Mail
|http://camel.apache.org/irc.html[camel-irc] |IRC
|http://camel.apache.org/jbpm.html[camel-jbpm] |jBPM
|http://camel.apache.org/jdbc.html[camel-jdbc] |JDBC
|http://camel.apache.org/jms.html[camel-jms] |JMS
|http://camel.apache.org/jmx.html[camel-jmx] |JMX
|http://camel.apache.org/jsch.html[camel-jsch] |SCP
|http://camel.apache.org/ldap.html[camel-ldap] |LDAP
|http://camel.apache.org/linkedin.html[camel-linkedin] |LinkedIn
|http://camel.apache.org/mqtt.html[camel-mqtt] |MQTT
|http://camel.apache.org/mustache.html[camel-mustache] |Mustache
|http://camel.apache.org/netty4.html[camel-netty4] |Netty
|http://camel.apache.org/netty-http.html[camel-netty4-http] |Netty HTTP
|http://camel.apache.org/olingo2.html[camel-olingo2] |OData 2.0 services using Apache Olingo 2.0
|http://camel.apache.org/paho.html[camel-paho] |Paho/MQTT
|http://camel.apache.org/pdf.html[camel-pdf] |PDF
|http://camel.apache.org/pgevent.html[camel-pgevent] |PostgreSQL events, LISTEN/NOTIFY
|http://camel.apache.org/printer.html[camel-printer] |Printer
|http://camel.apache.org/quartz2.html[camel-quartz2] |Quartz
|http://camel.apache.org/rabbitmq.html[camel-rabbitmq] |RabbitMQ
|http://camel.apache.org/rss.html[camel-rss] |RSS
|http://camel.apache.org/smpp.html[camel-smpp] |SMPP
|http://camel.apache.org/snmp.html[camel-snmp] |SNMP
|http://camel.apache.org/sql-component.html[camel-sql] |SQL
|http://camel.apache.org/ssh.html[camel-ssh] |SSH
|http://camel.apache.org/stomp.html[camel-stomp] |STOMP
|http://camel.apache.org/stream.html[camel-stream] |Input/output/error/file stream
|http://camel.apache.org/twitter.html[camel-twitter] |Twitter
|http://camel.apache.org/velocity.html[camel-velocity] |Velocity
|http://camel.apache.org/vertx.html[camel-vertx] |Vert.x
|http://camel.apache.org/weather.html[camel-weather] |Open Weather Map
|http://camel.apache.org/websocket.html[camel-websocket] |Websocket
|http://camel.apache.org/xmpp.html[camel-xmpp] |XMPP/Jabber
|http://camel.apache.org/xquery-endpoint.html[camel-saxon] |XQuery template
|===

.Camel data formats out of the box
[width="75%"]
|===
|Data format |Description

|http://camel.apache.org/xstream.html[camel-xstream] |XStream
|http://camel.apache.org/json.html[camel-jackson] |JSON
|http://camel.apache.org/soap.html[camel-soap] |SOAP
|http://camel.apache.org/csv.html[camel-csv] |CSV
|http://camel.apache.org/tar-dataformat.html[camel-tarfile] |Tar format
|http://camel.apache.org/crypto.html[camel-crypto] |Java Cryptographic Extension
|http://camel.apache.org/syslog.html[camel-syslog] |Syslog
|http://camel.apache.org/ical.html[camel-ical] |ICal
|http://camel.apache.org/barcode-data-format.html[camel-barcode] |Barcodes (QR-Code, etc.)
|===
