= {sponge} gRPC API
The {sponge} gRPC API allows users to remotely subscribe to {sponge} events.

The gRPC has been chosen to provide event subscriptions because the main remote {sponge} API, that is REST, has limited options for push notifications. The {sponge} gRPC API can be seen as an addition to the {sponge} REST API.

NOTE: Events are pushed online, i.e. if a client subscribes to an event type, only events that come after that time will be delivered.

== Operations summary
The following table contains a summary of the gRPC API operations.

.The gRPC API operations summary
[cols="2,1,4"]
|===
|Name |URI |Description

|Get the Sponge version
|`GetVersion`
|Returns the Sponge version.

|Subscribe events
|`Subscribe`
|Subscribes to {sponge} events and returns a stream of events.

|Subscribe events and manage a subscription
|`SubscribeManaged`
|Subscribes to {sponge} events and returns a stream of events. A subscription is managed by a stream of requests. This operation uses bidirectional steaming and is not supported in https://grpc.io/blog/state-of-grpc-web/[web gRPC clients].
|===

== Interface specification

.The protobuf file for the gRPC API
[source]
----
include::{includesRootDir}/sponge-grpc-api-common/src/main/proto/sponge.proto[lines=17..-1]
----

== Configuration
The convention is that the gRPC server port is the REST API port plus `1`, e.g. if the REST API port is `8080` then the gRPC API port will be `8081`.

== Error handling
An application error is returned to a client in a response message, just like in the REST API. An internal error is returned as a gRPC exception with a status.
