= Event processors
Event processors are processors that perform asynchronous operations using events they listen to.

Instances of event processors, depending on their type, may be created:

* only once, while enabling, so they are treated as singletons,
* many times.

.Event processors
[width="50%"]
|===
|Event processor |Singleton

|Filter
|Yes

|Trigger
|Yes

|Rule
|No

|Correlator
|No
|===

Filters and triggers are singletons, i.e. there is only one instance of one processor in the engine. However there can be many instances of one rule or one correlator in the engine.

When configuring an event processor, each event name can be specified as a regular expression thus creating a pattern matching more event names. The regular expression has to be compatible with {javaSeJavaDocUrl}/java/util/regex/Pattern.html[`java.util.regex.Pattern`].

.Event name pattern example
[source,python]
----
class TriggerA(Trigger):
    def onConfigure(self):
        self.withEvent("a.*") # <1>
    def onRun(self, event):
        self.logger.debug("Received event: {}", event.name)
----
<1> The trigger will listen to all events whose name starts with `"a"`, as specified by the regular expression.

Event processors shouldn't implement infinite loops in their callback methods because it would at least disrupt the shutdown procedure. If you must create such a loop, please use for example `while sponge.engine.isRunning():` rather than `while True:`.
