= {sponge} REST API server
The {sponge} REST API provides users a remote access to the key {sponge} functionalities. The REST API server plugin (`RestApiServerPlugin`) uses Apache Camel REST DSL in order to configure the JSON/REST service. After starting the plugin, the online API specification in the https://swagger.io[Swagger] JSON format will be available at URL `http://localhost:1836/api-doc`.

The default name of the REST API plugin (which can be used in knowledge bases) is `restApiServer`.

.Key REST API plugin configuration parameters
[cols="1,1,4"]
|===
|Name |Type |Description

|`autoStart`
|`boolean`
|If `true` then the REST service will start when the plugin starts up. Defaults to `true`.

|`restComponentId`
|`String`
|The Camel REST component id. Defaults to `"jetty"`.

|`host`
|`String`
|The REST API host.

|`port`
|`int`
|The REST API port. Defaults to `1836`.

|`prettyPrint`
|`boolean`
|The pretty print option. Defaults to `false`.

|`publicActions`
|`List<ProcessorQualifiedName>`
|Public actions.

|`publicEvents`
|`List<String>`
|Public event names.

|`sslConfiguration`
|`SslConfiguration`
|The SSL configuration.

|`publishReload`
|`boolean`
|If `true` then the reload operation will be published. Defaults to `false`.

|`routeBuilderClass`
|`String`
|The name of the class extending `RestApiRouteBuilder` (which is the default route builder).

|`apiServiceClass`
|`String`
|The `RestApiService` implementation class name. Defaults to `DefaultRestApiService`.

|`securityServiceClass`
|`String`
|The `RestApiSecurityService` implementation class name. Defaults to `NoSecuritySecurityService`.

|`authTokenServiceClass`
|`String`
|The `RestApiAuthTokenService` implementation class name. The default implementation is `JwtRestApiAuthTokenService` that uses JSON Web Token (JWT) for Java https://github.com/jwtk/jjwt[JJWT] library.

|`authTokenExpirationDurationSeconds`
|`Long`
|The duration (in seconds) after which an authentication token will expire. Defaults to `null` which means infinity.
|===

.The REST API server plugin XML configuration example
[source,xml,subs="verbatim,attributes"]
----
<sponge>
    <plugins>
        <plugin name="restApiServer" class="org.openksavi.sponge.restapi.server.RestApiServerPlugin">
            <configuration>
                <port>1836</port>
                <autoStart>false</autoStart>
            </configuration>
        </plugin>
    </plugins>
</sponge>
----

.The REST API server plugin Java configuration example
[source,java]
----
@Configuration
public static class Config extends SpongeCamelConfiguration {

    @Bean
    public SpongeEngine spongeEngine() {
        return SpringSpongeEngine.builder().plugins(camelPlugin(), restApiPlugin())
                .config("sponge_config.xml").build();
    }

    @Bean
    public RestApiServerPlugin restApiPlugin() {
        RestApiServerPlugin plugin = new RestApiServerPlugin();
        plugin.setSecurityService(restApiSecurityService());

        return plugin;
    }

    @Bean
    public RestApiSecurityService restApiSecurityService() {
        return new SimpleInMemorySecurityService();
    }
}
----

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/restapi/server/RestApiServerPlugin.html[`RestApiServerPlugin` Javadoc].

The REST API plugin provides a simple predefined knowledge base libraries: `engine_admin_library.py` and `engine_public_library.py`.

.Example use of the REST API predefined knowledge base library
[source,xml]
----
<knowledgeBase name="security" label="Security">
    <file>classpath:org/openksavi/sponge/restapi/server/engine_admin_library.py</file>
</knowledgeBase>
----

[discrete]
== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-rest-api-server</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

Depending on the REST Camel component, you should add a corresponding dependency, e.g. `camel-jetty` for Jetty, `camel-servlet` for a generic servlet. For more information see the Camel documentation.

== Operations summary
The following table contains a summary of the REST API operations. For a complete list of operations see the <<_swagger_overview, specification>> generated using Swagger and http://swagger2markup.github.io/swagger2markup/1.3.3/[Swagger2Markup].

.The REST API operations summary
[cols="2,1,4"]
|===
|Name |URI |Description

|Get the Sponge version
|`version`
|Returns the Sponge version.

|Login
|`login`
|User login. Used in a token-based authentication scenario.

|Logout
|`logout`
|User logout. Used in a token-based authentication scenario.

|Get knowledge bases
|`knowledgeBases`
|Returns the knowledge bases which the user may use (i.e. may call actions registered in these knowledge basses).

|Get actions
|`actions`
|Returns the metadata of actions that are available to the user. If you want to get metadata for specified actions, set the request property `name` to an action name or a Java-compatible regular expression. If you want to get only actions that have argument and result metadata specified in their configuration, set the request property `metadataRequired` to `true` (defaults to `false`). Actions will be sorted by a category sequence number, a knowledge base sequence number and an action label or name. The sequence number reflects the order in which categories or knowledge bases have been added to the engine.

|Call an action
|`call`
|Calls an action.

|Provide action arguments
|`actionArgs`
|Returns _provided arguments_, i.e. values along with value sets of action arguments. The request accepts the following properties: `name` - the action name, `argNames` -  the optional list of argument names that are to be provided (if `null`, all provided arguments will be produced), `current` - the optional map of argument names and their current values passed from a client code.

|Send a new event
|`send`
|Sends a new event.

|Reload knowledge bases
|`reload`
|Reloads all knowledge bases. Depending on the configuration, this operation may not be published. It should be available only to administrators.
|===

== JSON/Java mapping
The REST API uses the https://github.com/FasterXML/jackson[Jackson] library to process JSON. A transformation of action arguments and result values is determined by types specified in the corresponding action arguments and result metadata.

The default Jackson configuration for the REST API sets the ISO8601 format for dates.

NOTE: A `BinaryType` value is marshalled to a base64 encoded string. This encoding adds significant overhead and should be used only for relatively small binary data.

== Requests and responses
Each request may contain base properties.

.Base request properties
[cols="2,1,4"]
|===
|Name |Required |Description

|`id`
|No
|A request identifier. If it is present, the response will contain the same `id` property with the same value. This feature provides some compatibility with the JSON-RPC protocol.

|`username`
|No
|A user name that may be used in a user/password authentication mode. In that case, if there is no user name present, the _anonumous_ user is assumed.

|`password`
|No
|A user password that may be used in a user/password authentication mode.

|`authToken`
|No
|An authentication token that may be used in a token-based authentication mode.
|===

The {sponge} REST API supports both POST and GET methods.

.Examples of REST API requests
[source,bash]
----
curl -i -k -X POST -H "Content-type:application/json" http://localhost:1836/sponge.json/v1/version
curl -i -k -X POST -H "Content-type:application/json" http://localhost:1836/sponge.json/v1/knowledgeBases
curl -i -k -X POST -H "Content-type:application/json" http://localhost:1836/sponge.json/v1/actions
curl -i -k -X POST -H "Content-type:application/json" http://localhost:1836/sponge.json/v1/actions -d '{"username":"john","password":"password"}'
curl -i -k -X POST -H "Content-type:application/json" http://localhost:1836/sponge.json/v1/actions -d '{"name":".*Case"}'
curl -i -k -X POST -H "Content-type:application/json" http://localhost:1836/sponge.json/v1/call -d '{"name":"UpperCase","args":["test1"]}'
curl -i -k -X POST -H "Content-type:application/json" http://localhost:1836/sponge.json/v1/send -d '{"name":"alarm","attributes":{"a1":"test1","a2":"test2", "a3":4}}'
curl -i -k -X POST -H "Content-type:application/json" http://localhost:1836/sponge.json/v1/reload

curl http://localhost:1836/sponge.json/v1/version
curl http://localhost:1836/sponge.json/v1/knowledgeBases
curl -G "http://localhost:1836/sponge.json/v1/call" --data-urlencode 'request={"name":"OutputStreamResultAction","args":[]}'
----

== Security
The REST API provides only simple security out of the box and only if turned on. All requests allow passing a user name and a password. If the user name is not set, the _anonymous_ user is assumed. A user may have roles.

You may set a security strategy by providing an implementation of the `RestApiSecurityService` interface. You may find a few examples of such implementations in the source code. In production mode we suggest using https://spring.io/projects/spring-security[Spring Security] and configure Camel security. An advanced security configuration has to be set up in Java rather than in a {sponge} XML configuration file. You may implement various authorization scenarios, for example using HTTP headers that are available in a Camel exchange.

=== Authentication mode
Only a username/password authentication mode is currently supported by the default REST API service implementation.

.Authentication modes
[cols="1,4"]
|===
|Name |Description

|Username/password
|Every request has to contain a username and a password. Invoking the `login` operation switches to the authentication token mode.

|Authentication token
|Every request has to contain an authentication token, returned by the `login` operation. It may not contain neither username nor password.
|===

[[rest-api-server-simple-security-strategy]]
=== Simple security strategy
The simple security strategy uses in-memory user data. User privileges and access to knowledge bases, actions and events are verified by calling {sponge} actions (`RestApiIsActionPublic`, `RestApiIsEventPublic`, `RestApiCanUseKnowledgeBase`, `RestApiCanSendEvent`). Passwords are stored as SHA-256 hashes.

.Example of the REST API simple security
[source,python]
----
from org.openksavi.sponge.restapi.server.security import User

# Simple access configuration: role -> knowledge base names regexps.
ROLES_TO_KB = { "admin":[".*"], "guest":["mpd"], "anonymous":["mpd"]}

class RestApiCanUseKnowledgeBase(Action):
    def onCall(self, user, kbName):
        return restApiServer.canUseKnowledgeBase(ROLES_TO_KB, user, kbName)

def onStartup():
    # Set up users. To hash a password use (on Mac): echo -n <username><password> | shasum -a 256 | awk '{ print $1 }'
    # Note that the user name must be lower case.
    securityService = restApiServer.service.securityService
    securityService.addUser(User("john", "4ae0aa2783d6e8a939b0a3ce8146400001ef6b9840958aea136b416c58a2f9b8", ["admin"]))
    securityService.addUser(User("joe", "e52abe94e1e06f794a3654e02bfbe71565025ea6ce2898d1ad459182f3bc147b", ["guest"]))
----

For more information see examples in the source code.

== HTTPS
In production mode you should configure HTTPS, preferably using a signed certificate. Otherwise your passwords could be sent in plain text over the network as a part of the REST API JSON requests.

include::user-guide-rest-api.adoc[leveloffset=+1]

== Environment

=== Standalone
This is the default configuration that uses the embedded Jetty server.

=== Servlet container
The {sponge} REST API service may also be deployed into a servlet container (e.g. https://tomcat.apache.org[Tomcat]) as a web application. See the <<rest-api-demo-service,REST API Demo Service>> example.
