= {sponge} REST API server
The REST API server provides a {sponge} REST API service. The server plugin (`RestApiServerPlugin`) uses Apache Camel REST DSL in order to configure the JSON/REST service.

The default name of the REST API plugin (which can be used in knowledge bases) is `restApiServer`.

.Key REST API plugin configuration parameters
[cols="1,1,4"]
|===
|Name |Type |Description

|`autoStart`
|`boolean`
|If `true` then the REST service will start when the plugin starts up. Defaults to `true`.

|`restComponentId`
|`String`
|The Camel REST component id. Defaults to `"jetty"`.

|`host`
|`String`
|The REST API host.

|`port`
|`int`
|The REST API port. Defaults to `1836`.

|`prettyPrint`
|`boolean`
|The pretty print option. Defaults to `false`.

|`publicActions`
|`List<ProcessorQualifiedName>`
|Public actions.

|`publicEvents`
|`List<String>`
|Public event names.

|`sslConfiguration`
|`SslConfiguration`
|The SSL configuration.

|`publishReload`
|`boolean`
|If `true` then the reload operation will be published. Defaults to `false`.

|`routeBuilderClass`
|`String`
|The name of the class extending `RestApiRouteBuilder` (which is the default route builder).

|`apiServiceClass`
|`String`
|The `RestApiService` implementation class name. Defaults to `DefaultRestApiService`.

|`securityServiceClass`
|`String`
|The `RestApiSecurityService` implementation class name. Defaults to `NoSecuritySecurityService`.

|`authTokenServiceClass`
|`String`
|The `RestApiAuthTokenService` implementation class name. The default implementation is `JwtRestApiAuthTokenService` that uses JSON Web Token (JWT) for Java https://github.com/jwtk/jjwt[JJWT] library. Note that tokens used by the default implementation are signed but not encrypted.

|`authTokenExpirationDurationSeconds`
|`Long`
|The duration (in seconds) after which an authentication token will expire. The value `null` or less than or equal to 0 means infinity. Defaults to 30 minutes.

|`includeResponseTimes`
|`boolean`
|The flag specifying if a response header should have request and response time set. Defaults to `true`.
|===

.The REST API server plugin XML configuration example
[source,xml,subs="verbatim,attributes"]
----
<sponge>
    <plugins>
        <plugin name="restApiServer" class="org.openksavi.sponge.restapi.server.RestApiServerPlugin">
            <configuration>
                <port>1836</port>
                <autoStart>false</autoStart>
            </configuration>
        </plugin>
    </plugins>
</sponge>
----

.The REST API server plugin Java configuration example
[source,java]
----
@Configuration
public static class Config extends SpongeCamelConfiguration {

    @Bean
    public SpongeEngine spongeEngine() {
        return SpringSpongeEngine.builder().plugins(camelPlugin(), restApiPlugin())
                .config("sponge_config.xml").build();
    }

    @Bean
    public RestApiServerPlugin restApiPlugin() {
        RestApiServerPlugin plugin = new RestApiServerPlugin();
        plugin.setSecurityService(restApiSecurityService());

        return plugin;
    }

    @Bean
    public RestApiSecurityService restApiSecurityService() {
        return new SimpleInMemorySecurityService();
    }
}
----

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/restapi/server/RestApiServerPlugin.html[`RestApiServerPlugin` Javadoc].

The REST API plugin provides a simple predefined knowledge base libraries: `engine_admin_library.py` and `engine_public_library.py`.

.Example use of the REST API predefined knowledge base library
[source,xml]
----
<knowledgeBase name="security" label="Security">
    <file>classpath:org/openksavi/sponge/restapi/server/engine_admin_library.py</file>
</knowledgeBase>
----

[discrete]
== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-rest-api-server</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

Depending on the REST Camel component, you should add a corresponding dependency, e.g. `camel-jetty` for Jetty, `camel-servlet` for a generic servlet. For more information see the Camel documentation.

== Custom operations
You can define a custom REST API operation (using the `ActionDelegateRestApiOperation` class in the route builder) that delegates a REST API request to an action call (e.g. to allow implementing an operation body in a scripting language but keeping a static REST interface).

== OpenAPI specification
After starting the plugin, the online API specification in the https://swagger.io[OpenAPI 2.0 (Swagger)] JSON format will be accesible.

== JSON/Java mapping
The REST API uses the https://github.com/FasterXML/jackson[Jackson] library to process JSON. A transformation of action arguments and result values is determined by types specified in the corresponding action arguments and result metadata.

The default Jackson configuration for the REST API sets the ISO8601 format for dates.

NOTE: A `BinaryType` value is marshalled to a base64 encoded string. This encoding adds significant overhead and should be used only for relatively small binary data.

== Session
For each request the REST API service creates a thread local session. The session provides access to a logged user and a Camel exchange for a thread handling the request. The session can be accessed in an action via the REST API server plugin.

.Accessing the REST API session
[source,python]
----
class LowerCaseHello(Action):
    def onConfigure(self):
        self.withLabel("Hello with lower case")
        self.withArg(StringType("text").withLabel("Text to lower case")).withResult(StringType().withLabel("Lower case text"))
    def onCall(self, text):
        return "Hello " + restApiServer.session.user.name + ": " + text.lower()
----

== API features

.Remote API features
[cols="2,1,4"]
|===
|Name |Type |Description

|`grpcEnabled`
|`Boolean`
|Set to `true` if the optional {sponge} gRPC API service is enabled.
|===

== Security
The REST API provides only simple security out of the box and only if turned on. All requests allow passing a user name and a password. If the user name is not set, the _anonymous_ user is assumed.

A user may have roles.

You may set a security strategy by providing an implementation of the `RestApiSecurityService` interface. You may find a few examples of such implementations in the source code. In production mode we suggest using https://spring.io/projects/spring-security[Spring Security] and configure Camel security. An advanced security configuration has to be set up in Java rather than in a {sponge} XML configuration file. You may implement various authorization scenarios, for example using HTTP headers that are available in a Camel exchange.

[[rest-api-server-simple-security-strategy]]
=== Simple security strategy
The simple security strategy uses in-memory user data. User privileges and access to knowledge bases, actions and events are verified by calling {sponge} actions (`RemoteApiIsActionPublic`, `RemoteApiIsEventPublic`, `RemoteApiCanUseKnowledgeBase`, `RemoteApiCanSendEvent`, `RemoteApiCanSubscribeEvent`). Passwords are stored as SHA-512 hashes.

.Example of the Remote API simple security
[source,python]
----
from org.openksavi.sponge.restapi.server.security import User

# Simple access configuration: role -> knowledge base names regexps.
ROLES_TO_KB = { "admin":[".*"], "anonymous":["demo", "digits", "demoForms.*"]}
# Simple access configuration: role -> event names regexps.
ROLES_TO_SEND_EVENT = { "admin":[".*"], "anonymous":[]}
ROLES_TO_SUBSCRIBE_EVENT = { "admin":[".*"], "anonymous":["notification.*"]}

class RemoteApiCanUseKnowledgeBase(Action):
    def onCall(self, userContext, kbName):
        return restApiServer.canAccessResource(ROLES_TO_KB, userContext, kbName)

class RemoteApiCanSendEvent(Action):
    def onCall(self, userContext, eventName):
        return restApiServer.canAccessResource(ROLES_TO_SEND_EVENT, userContext, eventName)

class RemoteApiCanSubscribeEvent(Action):
    def onCall(self, userContext, eventName):
        return restApiServer.canAccessResource(ROLES_TO_SUBSCRIBE_EVENT, userContext, eventName)

def onStartup():
    # Setup users. To hash a password use (on Mac): echo -n username-password | shasum -a 512 | awk '{ print $1 }'
    # Note that the user name must be lower case.
    securityService = restApiServer.service.securityService
    securityService.addUser(User("john", "f4f28d85c27f6038bbdd2c8c73c4c2d2ca21350b368431b641999d3f6e1a38a474bae4b6856556532b30fc36a72272be4922ebe3d3b720ee3224b6bb7ced79b4", ["admin"]))
----

For more information see examples in the source code.

== HTTPS
In production mode you should configure HTTPS. Otherwise your passwords could be sent in plain text over the network as a part of the REST API JSON requests.

== Environment

=== Standalone
This is the default configuration that uses the embedded Jetty server.

=== Servlet container
The {sponge} REST API service may also be deployed into a servlet container (e.g. https://tomcat.apache.org[Tomcat]) as a web application. See the <<rest-api-demo-service,REST API Demo Service>> example.
