= {sponge} REST API client for Java
The {sponge} REST API client for Java simplifies connecting to a remote {sponge} REST API server from applications written in Java. The default implementation uses the http://square.github.io/okhttp/[OkHttp] library. The REST API client uses POST methods.

.REST API client for an anonymous user
[source,java]
----
try (SpongeRestClient client = new DefaultSpongeRestClient(SpongeRestClientConfiguration.builder()
        .url("http://localhost:8080/sponge.json/v1")
        .build())) { // <1>
    String upperCaseText = client.call(String.class, "UpperCase",  Arrays.asList("text")); // <2>
}
----
<1> Create a new REST API client.
<2> Call the remote action.

.REST API client for a named user
[source,java]
----
SpongeRestClient client = new DefaultSpongeRestClient(SpongeRestClientConfiguration.builder()
        .url(String.format("http://localhost:%d/%s", PORT, RestApiConstants.DEFAULT_PATH))
        .username(username)
        .password(password)
        .build());
----

`DefaultSpongeRestClient` performs best when you create a single instance and reuse it for all of your REST API calls.

For more information see the {spongeJavaDocUrl}/org/openksavi/sponge/restapi/client/DefaultSpongeRestClient.html[`DefaultSpongeRestClient` Javadoc] and examples in the source code.

[discrete]
== Maven configuration
Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.openksavi.sponge</groupId>
    <artifactId>sponge-rest-api-client</artifactId>
    <version>{projectVersion}</version>
</dependency>
----

