= Overview
:page-permalink: index.html

== {sponge}
*{sponge} is an open-source, Java-based Event Processing System.*

This documentation applies to version {projectVersion} (release date: {projectDate}).

{sponge} provides a software framework for implementing event processors that listen to certain events and perform specified operations when some conditions are met. Events are usually sent by external systems. The Event Processing System allows to introduce temporal and logical conditions to processed events. Event processing may end up with sending of another, high-level event thus creating a hierarchical model of events. The supported event processors include filters, triggers, rules and correlators.

Event processors are defined in knowledge bases. Knowledge base is defined in files which may be written in one of several supported scripting languages, i.e. Python, Ruby, Groovy, JavaScript as well as in Java or Kotlin.

{sponge} may be classified as a https://en.wikipedia.org/wiki/Complex_event_processing[Complex Event Processing] system.

{sponge} requires Java 1.8 or above.

{sponge} has been created by https://www.softelnet.com[Softelnet]. The project pages are hosted at {homepage}. The source code is hosted at https://github.com/softelnet/sponge[Github].

[quote, Oxford Dictionaries, 'https://en.oxforddictionaries.com/definition/sponge[Sponge]']
____
A primitive sedentary aquatic invertebrate with a soft porous body that is typically supported by a framework of fibres or calcareous or glassy spicules. Sponges draw in a current of water to extract nutrients and oxygen.
____

== Features
The main features of {sponge}:

* provides a concurrent processing of incoming events,
* allows generating and scheduling of events (e.g. supports cron notation),
* supports writing knowledge bases in several scripting languages,
* there is no need to learn yet another notation/DSL, however you have to learn at least the basics of the {sponge} API,
* allows embedding in a custom Java application (using Maven) or could be used as a standalone command-line application,
* supports connecting with a large number of external systems by integration with http://camel.apache.org[Apache Camel],
* provides own Apache Camel component for including {sponge} engine in a Camel route,
* supports creation of custom plugins (e.g. built-in plugin for integration with Camel),
* supports deployment in enterprise environments by integration with Spring framework,
* provides the standalone command-line application, that, for example, allows management of Camel routes without the need of writing Java code (you may use any of the supported scripting languages or XML),
* supports reloading of knowledge bases on the fly (i.e. while the system is running),
* events may represent such diverse entities as, for example, SNMP traps, RSS feeds or MIDI messages,
* may be used as a sandbox for learning multiple scripting languages,
* provides a comprehensive documentation and many examples.

== License
The {sponge} standard libraries are released under the https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 license]. However some optional {sponge} libraries and the {sponge} standalone command-line application are licensed under the https://www.gnu.org/licenses/gpl.html[GNU General Public License, Version 3] because they use optional, third-party libraries that require it.

== Applications
{sponge} could be used as a component in various types of applications. Here are some examples.

https://en.wikipedia.org/wiki/Internet_of_things[Internet of Things (IoT)]::
{sponge} as a part of https://en.wikipedia.org/wiki/Gateway_(telecommunications)#IoT_Modular_Gateway[an IoT gateway] may locally process data provided by the devices in the field, thus only important data is sent to the central node, where data is collected, stored and manipulated by enterprise applications.

https://en.wikipedia.org/wiki/Business_activity_monitoring[Business Activity Monitoring (BAM)]::
{sponge} embedded in a Spring based application may have an access to a service layer via Spring beans. {sponge} could periodically run monitoring tasks and generate notification events if necessary.

https://en.wikipedia.org/wiki/Fault_management[Fault management]::
{sponge} may be used to process faults or events sent by the network using a protocol such as SNMP. The processing may include creating issues into https://en.wikipedia.org/wiki/Issue_tracking_system[the issue tracking system (Trouble Ticket system)]. {sponge} may use all protocols supported by Apache Camel or provided by custom plugins.

https://en.wikipedia.org/wiki/Network_monitoring[Network monitoring]::
{sponge} may be used to monitor a web server by periodically sending an HTTP request to fetch a page. It may also provide more advanced checks by running for example http://www.seleniumhq.org[Selenium] scripts to verify a web application. When a problem is detected {sponge} could send an email to the administrator.

https://en.wikipedia.org/wiki/SCADA[Supervisory control and data acquisition (SCADA)]::
{sponge} may be used as a part of Alarm handling as well as a part of a module that connects to the remote terminal units (RTUs) or the field sensors and actuators.

https://en.wikipedia.org/wiki/Distributed_control_system[Distributed control system (DCS)]::
{sponge} may be used as a part of the production control level to provide an event-driven monitoring.

https://en.wikipedia.org/wiki/System_integration[System integration]::
{sponge} may be used to provide a script-based integration using Apache Camel routes. {sponge} could be connected to https://en.wikipedia.org/wiki/Enterprise_service_bus[the Enterprise Service Bus (ESB)] as well.

== Users
The potential users of an embedded {sponge} are Java developers.

The potential users of a standalone command-line {sponge} application are:

* Python, Ruby, Groovy or JavaScript developers,
* Java developers (for example for prototyping),
* system administrators.

Because of {sponge} is a Java-based solution, at least basic knowledge of Java is suggested. It becomes important when browsing Javadoc API, using Java libraries, analyzing exception stack traces, etc. Moreover, to effectively use {sponge} for problems that require integration, a knowledge of Apache Camel routes becomes important.

== Considerations

* {sponge} provides no graphical user interface (GUI).
* Because of {sponge} doesn't introduce its own notation for knowledge bases, it provides a shorter learning curve for users that know one of the supported scripting languages. However it could lack more sophisticated features and could be less optimized for certain uses than other solutions. For example you specify event conditions by writing any code in a scripting language that is to be executed when a matching event happens. On one hand it gives you a flexibility and on the other hand it doesn't provide optimizations that could be possible if, for example, a strict temporal reasoning notation is used.
* Currently {sponge} doesn't provide persistence out of the box.
