= Release notes
:page-permalink: /release-notes/

A high-level view of the changes introduced in {sponge} releases.

Unless noted otherwise in the release notes, {sponge} releases (starting with version 1.5.0) that have the same `major.minor` numbers are compatible.

[discrete]
== 1.9.1 (not released yet)
* Added new callback functions in knowledge bases: `onBeforeLoad` and `onAfterLoad`.
* Added support for registering data types (`EngineOperations` methods `addType`, `getType` and `getTypes`). A registered data type instance has its property `DataType.registeredType` set to a name of a registered type.
* Added support for `RecordType` inheritance.
* Added support for automatic use of auth tokens in the REST API client.
* Changed password hashing SHA-256 to SHA-512 in the REST API `BaseInMemoryKnowledgeBaseProvidedSecurityService` class.
* Changed the default auth token expiration time from infinity to 30 minutes in the REST API.
* Support for custom REST API operations.

[discrete]
== 1.9.0 (2019-04-15)

* API change: Renamed `fileName` to `filename`.
* API change: Introduced `RestApiSession` and `UserAuthentication` in the REST API server.
* Added a limited support for extending Java-based processors and plugins in non-Java knowledge bases.
* Added a new type `StreamType`.
* Added a new REST API error code `ERROR_CODE_INCORRECT_USERNAME_PASSWORD ("SPONGE004")`.
* Added a thread local session to the REST API service. The session provides access to a logged user and a Camel exchange.
* Fixed the bug that caused a `NullPointerException` when sending a record with a `null` value of a field in the REST API request.
* Moved the `sponge-mpd` dependency (GPL) from `sponge-standalone-extensions` to `sponge-distribution` and changed the `sponge-standalone-extensions` license to Apache.
* Dependencies upgrade.

[discrete]
== 1.8.0 (2019-03-04)

* API change: Action arguments and result metadata are now specified as data types. `ArgMeta` and `ResultMeta` classes have been removed.
* API change: The processor metadata properties, data type properties have to be specified using the builder-style methods, e.g. `self.withLabel("Label").withDescription("Description")`. The builder-style methods in the metadata classes follow the naming convention `with<Property>`, e.g. `BinaryType().mimeType("image/png")` is now `BinaryType().withMimeType("image/png")`.
* API change: Renamed `ArgProvidedMeta` to `ProvidedMeta`, `ArgProvidedValue` to `ProvidedValue` and `ProvidedMeta.depends` to `ProvidedMeta.dependencies`.
* API change: The `Action.onProvideArgs(names, current, provided)` has been changed to `Action.onProvideArgs(ProvideArgsContext context)`.
* API change: Removed `AnnotatedType`. Use `DataType.withAnnotated()` instead.
* Added support for categories. Processors may be assigned to registered categories.
* Added new types: `DynamicType`, `TypeType`, `DateTimeType`.
* Added `CategoryMeta.features` and a dynamic category selection for processors.
* Fixed the bug that caused an error when sending an empty body in the REST API request.
* Dependencies upgrade.

[discrete]
== 1.7.0 (2019-02-01)

* API change: Renamed `displayName` to `label`.
* API change: Renamed `ArgProvided` to `ArgProvidedMeta`, `ArgValue` to `ArgProvidedValue`.
* API change: A provided argument specification in now placed in the `ArgProvidedMeta` class, not directly in the `ArgMeta` as before.
* API change: Removed `LabeledValue` and `ArgProvidedValue.valueSetDisplayNames` because of a new support for an annotated value set.
* API change: Removed `inputString`, `inputBinary`, `inputFile`, `outputFile`, `errorFile`, `outputLineConsumer`, `errorLineConsumer` methods from the `ProcessConfigurationBuilder`. The preferred way to configure redirects is to use `inputAs...`, `outputAs...` and `errorAs...` methods.
* Added new methods `callIfExists` in the `EngineOperations`.
* Added `Processor.version` and verification of an action qualified version in the REST API.
* Dependencies upgrade.

[discrete]
== 1.6.0 (2019-01-11)

* A noteworthy new feature: There is a possibility to provide action argument values and possible value sets in the action configuration. It makes easier creating a generic UI for an action call that reads and presents the actual state of the entities that are to be changed by the action and its arguments.
* Added a new REST API operation `actionArgs` that fetches the provided action arguments from the server.
* API change: The action calling methods, e.g. `EngineOperations.call(String actionName, Object... args)` have been changed to `EngineOperations.call(String actionName, List<Object> args)` and `EngineOperations.call(String actionName)`. So for example the previous call `sponge.call("HelloWorldAction", "Sponge user")` should be now `sponge.call("HelloWorldAction", ["Sponge user"])`.
* API change: Renamed class `Type` to `DataType` and `TypeKind` to `DataTypeKind`.
* API change: Renamed classes in the REST API client, including `SpongeRestApiClient` to `SpongeRestClient` and `SpongeRestApiClientConfiguration` to `SpongeRestClientConfiguration`.
* API change: Removed `SpringSpongeRestClient` from the REST API client because the underlying Spring `RestTemplate` will be deprecated.
* API change: Renamed methods in `CamelPlugin`: `send(body)` to `emit(body)`, `send(uri, body)` to `sendBody(uri, body)` and `request(uri, body)` to `requestBody(uri, body)`.
* API change: Major changes in an external process handling, including `ProcessInstance` and `ProcessConfiguration`.
* API change: Removed alternative, deprecated methods for creating and sending events in `EngineOperations`.
* API change: Renamed `Event.getOrDefault` to `Event.get`.
* API change: Removed `ActionType` because there is a more versatile feature of providing action argument values and value sets.
* Added a new validation that an event name must not contain white spaces nor colons.
* The default value of the `prettyPrint` option in the REST API is now `false`.
* Added a context and listeners to the REST API client that provide access to JSON texts in a client code.
* Added a critical section in event handling by a correlator.
* Added a new property to correlators: `instanceSynchronous`.
* Added a new data type `AnnotatedType`.
* Documentation includes the REST API client for Dart.
* Improved error handling in the REST API server.
* Added the `-D` option in the standalone command-line application for passing Java system properties.
* Removed some of the Camel components from the standalone command-line application to reduce the overall package size.
* Cleanup in the Digits recognition example.
* Dependencies upgrade.

[discrete]
== 1.5.0 (2018-11-08)

* API change: Removed the `tags` property from a type (used in an action argument and in an action result metadata) because the existing `features` property is sufficient.
* API change: The `nameRegExp` property in the `GetActionsRequest` in the REST API has been renamed to `name`. The default value of the `metadataRequired` property is now `false`.
* Added the `optional` property to the `ArgMeta`.
* Action metadata cache in the REST API Java client.
* Fixed usage of OkHttpClient in the REST API Java client.
* Dependencies upgrade.

[discrete]
== 1.4.2 (2018-09-14)

* API change: `ArgMeta.required` in the REST API has been replaced by `Type.nullable`.
* Changes in the REST API Java client, e.g. a full URL instead of hostname/port in a configuration, support a the OkHttp-based client (default) and for a Spring-based client (optional).
* Enhancements in running external executable as a subprocess, e.g. binary redirect type, waiting for an error line from the subprocess text output.
* The REST API server `publishReload` configuration parameter has now the default value `false`.
* Dependencies upgrade.

[discrete]
== 1.4.1 (2018-08-22)

* API change: A processor `meta` property has been renamed to `features`.
* Optional knowledge base versioning.
* A type for an action argument or result metadata may specify one or more features.
* Dependencies upgrade.

[discrete]
== 1.4.0 (2018-08-01)

* API change: the `EPS` global variable for the engine operations has been renamed to `sponge`.
* A new REST API client artifact `sponge-rest-api-client`. The existing REST API server artifact has been renamed to `sponge-rest-api-server`.
* Optional auth-token based authentication in the REST API.
* A new artifact for TensorFlow integration `sponge-tensorflow` along with a complete example.
* Enhancements in Py4J plugin configuration for running external Python scripts as subprocesses.
* A type for an action argument or result metadata may specify one or more tags.
* Dependencies upgrade.

[discrete]
== 1.3.3 (2018-07-12)

* Added a new attribute to the REST API `actions` operation that allows specifying an action name or a regular expression.
* Added a new `ActionType` type that allows using a result of one action to be a type for another action argument or result.
* Fixed the error that may happen while loading optional knowledge base files if a directory doesnt't exist.
* The `sponge-core` artifact now shades the Reflections artifact (that use Guava).

[discrete]
== 1.3.2 (2018-07-06)

* Fixed the error that may happen while loading optional knowledge base files using the `SpringKnowledgeBaseFileProvider`.
* Libraries upgrade (most notably Spring to version 5).

[discrete]
== 1.3.1 (2018-07-04)

* Java-based processors may be enabled and disabled by scanning Java packages (`enableJavaByScan`).
* Knowledge base files may be specified using wildcards.
* Support for custom roles in the REST API. Roles are represented as String rather than an enumeration.
* Support for complex data types in the REST API. A type specification in action metadata has changed.
* Minor bug fixes.
* Dependencies upgrade.

[discrete]
== 1.3.0 (2018-06-20)

* API change: `Action.onCall` callback method behavior has been changed to dynamic. Custom actions define `onCall` methods with the arbitrary number of named arguments, for example `def onCall(self, value, text):` in Python.

[discrete]
== 1.2.0 (2018-06-18)

* API change: `Action.onCall` callback method signature has been changed to `Object onCall(Object[] args)`.
* A new Sponge REST API (`sponge-rest-api`) that uses JSON as its communication format.
* Support for simple metadata (map of `String` to `Object`) for processors.
* Support for metadata for arguments and results of actions.
* Support for pre/post config file plugins and knowledge bases in Engine Builder.
* Dependencies upgrade.

[discrete]
== 1.1.0 (2018-04-12)

* Support for using ReactiveX (`sponge-reactivex`) in knowledge bases, e.g. for processing a stream of {sponge} events using reactive programming.
* Added support for passing a knowledge base script as a String to the EngineBuilder API.
* Fixed the error preventing closing a standalone application when there was an exception thrown in `onShutdown` callback function in a knowledge base.
* Pi4J (`sponge-rpi-pi4j`) and GrovePi (`sponge-rpi-grovepi`) integration examples.
* Dependencies upgrade.

[discrete]
== 1.0.8 (2018-03-14)

* API change: The `Engine` interface has been renamed to `SpongeEngine`. The implementations have been renamed accordingly. The `EngineCamelConfiguration` class has been renamed to `SpongeCamelConfiguration`.
* Added a new callback function `onRun` to knowledge bases that allows a user to, for example, just run a script and stop the engine.
* Simplified specification of rule event conditions in Java and Kotlin.
* Added a simple support for Raspberry Pi: Pi4J (`sponge-rpi-pi4j`) and GrovePi (`sponge-rpi-grovepi`).

[discrete]
== 1.0.7 (2018-02-02)

* Added MIDI support. The MIDI plugin allows processing MIDI messages by the {sponge} and provides communication with MIDI devices.
* API change: The `Utils` class has been renamed to `SpongeUtils`.
* Added support for writing non script knowledge bases in Kotlin.
* Added support for specifying non script knowledge bases in an XML configuration.
* A type of a script knowledge base is no logger required in an XML configuration when knowledge base files are specified.
* The `sponge-core` artifact now shades Guava, so the `sponge-core-shaded` artifact has been removed since it is no longer needed.
* Downgraded Jython to version 2.7.0 to prevent stability issues.
* Added `sponge-external` group of projects in order to provide functionalities that require licenses incompatible with Apache 2.0.
* Added MPD support (in `sponge-external`, because it is GNU GPL 3.0 licensed).
* Dependencies upgrade.

[discrete]
== 1.0.6 (2017-12-01)

* The new, shaded version of sponge-core named sponge-core-shaded for an embedded use in custom applications that experience version conflicts in Guava or Quartz. Now you have to explicitly add a dependency to either sponge-core or sponge-core-shaded in your pom.xml.
* Support for integration with CPython using Py4J.
* The new startup system event.
* Dependencies upgrade.

[discrete]
== 1.0.5 (2017-10-12)

* API change: The `EngineOperations` method `callAction` has been renamed to `call`.
* The new attribute `required` in the knowledge base file configuration that, if set to false, allows specifying optional (non existing) knowledge base files.
* Script knowledge base files are looked up also in the file system relative to the XML configuration file parent directory.
* Abstract processor classes in script knowledge bases are now compatible with the auto-enable mechanism. The support for abstract processors is implemented for Python, Groovy, Ruby but not for JavaScript.
* CamelProducerAction may be also set in the Camel In message header named CamelSpongeAction.
* SpringEngine may be configured not to start immediately (see `SpringEngineBuilder.autoStartup` method).
* Improvements in the interactive mode of the standalone command-line application (now JLine is used, supporting for example a command history).
* Fixed the error preventing substitution of properties defined via the EngineBuilder API in the properties section in the XML configuration files.

[discrete]
== 1.0.4 (2017-09-20)

* Implementation of unordered rules, i.e. rules that listen to unordered sequences of events. Unordered rules is a new feature that should be treated as an experimental one.
* API change: The `Rule` methods `setConditions` and `setAllConditions` have been renamed respectively to `addConditions` and `addJavaConditions`.
* Fixed the error in the interactive mode of the standalone application preventing exit when using `exit` or `quit` command.
* Dependencies upgrade.
* Distribution as a Docker container.

[discrete]
== 1.0.3 (2017-08-30)

* Optimization of event set processors initialization.
* Optimization of creating new instances of processors in script-based interpreters.
* API change: `onInit` in correlators will be invoked after `onAcceptAsFirst`, not before.

[discrete]
== 1.0.2 (2017-08-23)

* Event name patterns in event processors.
* Removed `matches` method in `Event`.
* `EventDefinition` `send` methods accept `Duration` and `Instant` types.
* Fixed the concurrency problem in event set processors.
* New tests for scripting support.
* Dependencies upgrade.

[discrete]
== 1.0.1 (2017-08-21)

* Fixed the possible SyncAsyncEventSetProcessorMainProcessingUnitHandler concurrency error.

[discrete]
== 1.0.0 (2017-08-18)
The initial release.