= Sponge Developer Guide

== Maven

=== Settings

 export MAVEN_OPTS="-Xmx2048m"

=== Create all
This includes www project page contents and standalone distribution).

 cd sponge
 mvn clean install

The result directory is `sponge-distribution/sponge-{projectVersion}-www`. Change `package` to `install` to install in the local maven repository

=== Turn off specified profiles
This generates all but without tests, licenses, javadoc, documentation, review and assembly.

 mvn clean install -DskipTests -P-create-license-list -P-download-licenses -P-javadoc -P-documentation -P-review -P-assembly

=== Generate Jekyll source directory

The project pages are generated by https://jekyllrb.com[Jekyll], using a modified https://github.com/pages-themes/cayman[Cayman theme]. Favicon has been generated by http://realfavicongenerator.net[RealFaviconGenerator].

 # Create all, i.e. run 'mvn clean install' in sponge directory and then:
 cd sponge-distribution
 mvn package -Pjekyll

The generated source directory will be placed in target/jekyll/jekyll. Contents of this directory should be copied to the web server.

==== Testing project pages in Jekyll

 cd sponge-distribution/target/jekyll/jekyll
 bundle exec jekyll serve --host=0.0.0.0

If you get `ERROR: directory is already being watched!` message, simply ignore it. This is due to the use of symbolic link pointing to the root of the project.

=== Generate the documentation only

 cd sponge-distribution
 mvn generate-resources

=== Generate third party licenses info

 cd sponge-distribution
 mvn license:download-licenses license:add-third-party -Pcreate-license-list -Pdownload-licenses

=== Code review only

 mvn install -DskipTests -P-create-license-list -P-download-licenses -P-javadoc -P-documentation -P-assembly

== Code style
Formatter and checkstyle based on Google configuration.

Project specific files located in `sponge-development-tools`.

== Eclipse
Eclipse Oxygene (4.7.0) or above is recommended.

* Clone the repository.
* Import existing maven projects into the Eclipse.
* If there are error messages in Eclipse after the initial build, try to refresh all projects and run Maven/Update Project on all projects.
* Import code style settings and dictionary from /sponge-development-tools/eclipse/configuration.
* Go to Preferences/General/Editors/Text editors, check Insert spaces for tabs and set Show print margin: 140.
* Additionally you may want to set Java/Editor/Save actions: Format, Organize Imports, Remove trailing whitespaces, Correct indentation, Add missing annotations, Remove unused imports.

=== Eclipse plugins


