= Sponge Remote Privacy Policy

The Sponge Remote mobile app is an open-source app released under the Apache 2.0 license. It is at no cost and is intended for use as is.

This page is used to inform visitors regarding our policies with the possible collection, use, and disclosure of Personal Information if anyone decided to use our app to connect to a particular Sponge service.

If you choose to use our app to connect to a Sponge service, then you agree to the possible collection and use of information in relation to this policy. The Personal Information that can be collected is intended for providing a particular Sponge service unless a particular service provider states otherwise. The particular Sponge service provider is responsible for compliance with this Privacy Policy.

Note that the predefined Sponge application services are open-source as well, so you can evaluate their functionality by yourself.

== Information collection and use
The app can use third party services that may collect information used to identify you.

== Log data
We want to inform you that whenever you use our app, in a case of an error in the app we collect data and information on your phone called Log data. This Log data may include information such as your device Internet Protocol (IP) address, device name, operating system version, the configuration of the app when utilizing our app, the time and date of your use of the app and other statistics.

== Security
We value your trust in providing us your Personal Information. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.

== Children’s privacy
Some Sponge actions published in Sponge services may appeal to children under the age of 13, for example actions allowing a user to draw doodles on a mobile device. If you are a parent or guardian we advise you to supervise your child in such cases.

== Changes to this privacy policy
We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes.

This policy is effective as of 2020-07-23.

== Contact us
If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at softelnetmobile@gmail.com.

