= Sponge Developer Guide

== Maven

=== Settings

 export MAVEN_OPTS="-Xmx2048m"

== Build project

 cd sponge
 mvn clean install

=== Prepare a release
This step installs packages in the local Maven repository, generates documentation (AsciiDoc and JavaDoc), generates third party licenses info, creates standalone application ZIP archive and generates Jekyll source pages.

 mvn clean install -Pall,review,documentation,licenses,standalone,jekyll

In order to skip tests, run:

 mvn clean install -Pall,review,documentation,licenses,standalone,jekyll -DskipTests

=== Generate documentation only

 cd sponge-distribution
 mvn generate-resources -Pdocumentation

=== Generate third party licenses info

 cd sponge-distribution
 mvn license:download-licenses license:add-third-party -Plicenses

=== Generate Jekyll project pages
The project pages (located at {homepage}) are maintained and hosted by Softelnet.

The project pages are generated using https://jekyllrb.com[Jekyll] with https://github.com/asciidoctor/jekyll-asciidoc[AsciiDoc Plugin] and a modified https://github.com/pages-themes/cayman[Cayman theme]. Favicon has been generated by http://realfavicongenerator.net[RealFaviconGenerator]. To install these tools please follow their documentations.

 # First, create all, i.e. run 'mvn clean install -DskipTests -Pdocumentation,licenses,standalone' in sponge directory and then:
 cd sponge-distribution
 mvn package -Pjekyll

The generated source directory will be placed in target/jekyll/jekyll.

==== Building project pages in Jekyll

 cd sponge-distribution/target/jekyll/jekyll
 bundle exec jekyll build

The contents of the directory `_site` should be copied to the web server. Note: Building project pages in Jekyll has not been tested on Windows.

==== Testing project pages in Jekyll

 cd sponge-distribution/target/jekyll/jekyll
 bundle exec jekyll serve --host=0.0.0.0

If you get `ERROR: directory is already being watched!` message, simply ignore it. This is due to the use of symbolic link pointing to the root of the project.


== Code style
Formatter and checkstyle based on Google configuration.

Project specific files located in `sponge-development-tools`.

== Eclipse
Eclipse Oxygene (4.7.0) or above is recommended.

Configuration:

* Clone the repository.
* Import existing maven projects into Eclipse.
* If there are error messages in Eclipse after the initial build, try to refresh all projects and run Maven/Update Project on all projects.
* Import code style settings and dictionary from /sponge-development-tools/eclipse/configuration.
* Go to Preferences/General/Editors/Text editors, check Insert spaces for tabs and set Show print margin: 140.
* Additionally you may want to set Java/Editor/Save actions: Format, Organize Imports, Remove trailing whitespaces, Correct indentation, Add missing annotations, Remove unused imports.
