= Sponge Developer Guide

== Maven

=== Create all
This includes www project page contents and standalone distribution).

 cd sponge
 mvn clean install

The result directory is `sponge-distribution/sponge-{projectVersion}-www`. Change `package` to `install` to install in the local maven repository

=== Turn off specified profiles
This generates all but without tests, licenses, javadoc, documentation, review and assembly.

 mvn clean install -DskipTests -P-create-license-list -P-download-licenses -P-javadoc -P-documentation -P-review -P-assembly

=== Only generate the documentation

 cd sponge-distribution
 mvn generate-resources

=== Generate third party licenses info

 cd sponge-distribution
 mvn license:download-licenses license:add-third-party -Pcreate-license-list -Pdownload-licenses

=== Code review only

 mvn install -DskipTests -P-create-license-list -P-download-licenses -P-javadoc -P-documentation -P-assembly

== Code style
Formatter and checkstyle based on Google configuration.

Project specific files located in `sponge-development-tools`.

== Eclipse

=== Eclipse plugins

* http://dist.springsource.org/snapshot/GRECLIPSE/e4.7/[Groovy plugin for Eclipse Neon^]


