= Release notes

A high-level view of the changes introduced in {sponge} releases.

[discrete]
== 1.0.4 (2017.09.20)

* Implementation of unordered rules, i.e. rules that listen to unordered sequences of events. Unordered rules is a new feature that should be treated as an experimental one.
* API change: The `Rule` methods `setConditions` and `setAllConditions` has been renamed respectively to `addConditions` and `addJavaConditions`.
* Fixed error in the interactive mode of the standalone application preventing exit when using `exit` or `quit` command.
* Libraries upgrade.
* Distribution as a Docker container.

[discrete]
== 1.0.3 (2017.08.30)

* Optimization of event set processors initialization.
* Optimization of creating new instances of processors in script-based interpreters.
* API change: `onInit` in correlators will be invoked after `onAcceptAsFirst`, not before.

[discrete]
== 1.0.2 (2017.08.23)

* Event name patterns in event processors.
* Removed `matches` method in `Event`.
* `EventDefinition` `send` methods accept `Duration` and `Instant` types.
* Fixed concurrency problem in event set processors.
* New tests for scripting support.
* Libraries upgrade.

[discrete]
== 1.0.1 (2017.08.21)

* Fixed possible SyncAsyncEventSetProcessorMainProcessingUnitHandler concurrency error.

[discrete]
== 1.0.0 (2017.08.18)
The initial release.