= Sponge Developer Guide

Sponge sources can be built with Java 8.

== Maven

=== Settings

 export MAVEN_OPTS="-Xmx2048m"

== Build project

=== Prerequisites

* You have to manually install the https://github.com/DexterInd/GrovePi/tree/master/Software/Java8[Java 8 GrovePi library] in you local Maven repository because it isn't available in the Central Maven Repository. This library is used by `sponge-rpi-grovepi`.

=== Simple build

 cd sponge
 mvn clean install

=== Prepare a release
This step installs packages in the local Maven repository, generates documentation (AsciiDoc and Javadoc), generates third party licenses info, creates standalone application ZIP archive and generates Jekyll source pages.

 mvn clean install -Pall,review,documentation,licenses,standalone,docker,jekyll

In order to skip tests, run:

 mvn clean install -Pall,review,documentation,licenses,standalone,docker,jekyll -DskipTests

NOTE: The assertions in some tests heavily depend on the values of timeouts, durations, etc. and the speed of the test environment, therefore running the tests on a very slow machine may cause assertion failures that (in most cases) would not indicate bugs.

=== Generate OpenAPI documentation

 # Run the `RestApiServerMain` (located in `sponge-rest-api-server`).
 cd sponge-distribution
 mvn -Popenapi generate-sources
 # Stop the `RestApiServerMain`.

The generated file will be placed in `sponge-distribution/src/asciidoc/includes/user-guide-rest-api.adoc`. It will be automatically included in the main documentation.
 
=== Generate documentation only

 cd sponge-distribution
 mvn generate-resources -Pdocumentation

=== Generate third party licenses info

 cd sponge-distribution
 mvn license:download-licenses license:add-third-party -Plicenses

=== Generate Jekyll project pages
The project pages (located at {homepage}) are maintained and hosted by Softelnet.

The project pages are generated using https://jekyllrb.com[Jekyll] with https://github.com/asciidoctor/jekyll-asciidoc[AsciiDoc Plugin] and a modified https://github.com/pages-themes/cayman[Cayman theme]. Favicon has been generated by http://realfavicongenerator.net[RealFaviconGenerator]. To install these tools please follow their documentations.

 # First, build all in sponge and sponge-external directory and then:
 cd sponge-distribution
 mvn package -Pjekyll

The generated source directory will be placed in target/jekyll/jekyll.

==== Build project pages in Jekyll

 cd sponge-distribution/target/jekyll/jekyll
 bundle exec jekyll build

The contents of the directory `_site` should be copied to the web server. Note: Building project pages in Jekyll has not been tested on Windows.

==== Test project pages in Jekyll

 cd sponge-distribution/target/jekyll/jekyll
 bundle exec jekyll serve --host=0.0.0.0

If you get `ERROR: directory is already being watched!` message, simply ignore it. This is due to the use of symbolic link pointing to the root of the project.

=== Docker

==== Build Docker image

Remember to verify the Sponge version in Dockerfile in sponge-distribution/src/docker.

If necessary assembly Docker base directory.

 cd sponge-distribution
 mvn package -Pdocker
 cd ..

Build Docker image.

 cd sponge-distribution/target/docker/docker
 docker build -t openksavi/sponge:1.0.6 -t openksavi/sponge:latest .

==== Publish Docker image

After building the Docker image, execute (according to https://docs.docker.com/docker-cloud/builds/push-images/):

 docker login
 docker push openksavi/sponge

=== Performance tests
Performance tests have to be invoked manually, because they require more time to finish.

 cd sponge-integration-tests/
 mvn test -Dtest=org.openksavi.sponge.integration.tests.performance.LoadTest

=== Running the standalone application in Maven

 cd sponge-standalone/
 mvn exec:java -Dexec.args="-k examples/standalone/trigger_simple.py -i"

== Code style
Formatter and checkstyle based on Google configuration.

Project specific files located in `sponge-development-tools`.

== Eclipse
Eclipse Oxygene (4.7.0) or above is recommended.

Configuration:

* Clone the repository.
* Import existing maven projects into Eclipse.
* If there are error messages in Eclipse after the initial build, try to refresh all projects and run Maven/Update Project on all projects.
* Import code style settings and dictionary from /sponge-development-tools/eclipse/configuration.
* Go to Preferences/General/Editors/Text editors, check Insert spaces for tabs and set Show print margin: 140.
* Additionally you may want to set Java/Editor/Save actions: Format, Organize Imports, Remove trailing whitespaces, Correct indentation, Add missing annotations, Remove unused imports.
